### ISSUE TITLE
gbOPEN - MDG - ADM2

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#101]
MDG ADM2  was moved to humanitarian release. Need to find an alternative source for gbOPEN product.

**Comment by helenabuckman** [comment]
The license for this shapefile did not match the list of acceptable licenses for gbOpen. I have not been able to find another shapefile with the correct license. I emailed Professor Hijmans from Stanford for permission for his version of MDG ADM2 but I have not heard back yet. Will update if I get a response.

**Comment by slfuhrig** [comment]
https://data.humdata.org/dataset/madagascar-administrative-level-0-4-boundaries
