### ISSUE TITLE
gbOPEN - MOZ - ADM2

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#106]
MOZ ADM2 was moved to humanitarian release. Need to find an alternative source for gbOPEN product.

**Comment by sylviashea1** [comment]
Assigned to Hadley Day (not in gB Org yet)

**Comment by hadleyday** [comment]
Mozambique notes (before break)
Mozambique 2020 Updated Districts List 
Country Breakdown
Mozambique (ADM 0)
10 Provinces and 1 capital city (ADM 1)
128 Districts (ADM 2) 
405 Postos (ADM 3) 

Possible lead:
https://catalog.loc.gov/vwebv/staffView?searchId=1421&recPointer=0&recCount=25&searchType=1&bibId=16968032
Humanitarian Use Links:
https://data.humdata.org/dataset/mozambique-administrative-levels-0-3
