### ISSUE TITLE
Release metadata file for authoritative sources is misspelled (which messes with programmatic access)

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1067]
### What is the expected behavior?

The [release metadata file for authoritatitve sources](https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/geoBoundariesAuthoratative-meta.csv) should be spelled as "Author-i-tative". 

### What is the actual behavior?  The more detail the better.

Instead, the file is misspelled as "Author-a-tative", which messes with some api-stuff and programmatic access. 

### Other notes on how to reproduce the issue?

NA

### Any possible solutions?

Assuming the file is produced programmatically, correct the misspelling in the script responsible. 

[ ] I'll work on a PR for this!

**Comment by DanRunfola** [comment]
Nice catch, fixed.  https://github.com/wmgeolab/geoBoundaryBot/commit/f9aa6cfa14c4bf9ddc989c320ec8090f3159d4a8
