### ISSUE TITLE
Invalid urls/typos in metadata csv files

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1109]
### What is the expected behavior?
In the releaseData metadata csv files, the columns "licenseURL" and "boundarySourceURL" should contain valid urls. 

### What is the actual behavior?  The more detail the better.
The actual urls seem to be consistently missing the https colon, ie "https//www..." instead of "https://www...". 

### Any possible solutions?
Not sure if the error stems from manual input of the url or from a formattng error in the script producing the metadata csvs. 

[ ] I'll work on a PR for this!

**Comment by DanRunfola** [comment]
Confirming this one, will get it fixed for 4.0.

Some bigger issues with the CSV build script right now (specifically, it fails on seemingly random geometries for no reason during vertex counts), so will add this to the queue :)

**Comment by DanRunfola** [comment]
This has been fixed with https://github.com/wmgeolab/geoBoundaryBot/commit/25050c1d733853576a56064101578d192285d31b
