### ISSUE TITLE
[BOUNDARY ERRATA] missing shapes in ADM0

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1140]
I have a list of missing shapes, their names, and the ISO codes.  If we find contributions can these be included in v4?

ADM0

Aruba | ABW
Anguilla | AIA
Bermuda | BMU
Cook Islands | COK
Curacao | CUW
Cayman Islands | CYM
Faroe Islands | FRO
Guernsey | GGY
Gibraltar | GIB
Isle of Man | IMN
Jersey | JEY
Montserrat | MSR
New Caledonia | NCL
Niue | NIU
Pitcairn Islands | PCN
French Polynesia | PYF
Saint Helena, Ascension, and   Tristan da Cunha | SHN
Sint Maarten | SXM
Turks and Caicos Islands | TCA
Tokelau | TKL
British Virgin Islands | VGB
Wallis and Futuna | WLF
Gaza Strip | PSE
Svalbard | SJM

**Comment by DanRunfola** [comment]
Hey Lee,

Yes!  We plan on doing these ourselves post-4.0 release, but if we can find
appropriately licensed files that we could push in the next release I would
love to include them sooner than later.

Dan

**Comment by DanRunfola** [comment]
I have added these to the master "to cover" list over at the gB bot.  After 4.0, I'll be running a script to identify any missing ISO codes from the database.

Note I've also started adding claimant and disputed columns so as to denote what country claims the territory (i.e., DNK / GRL), and if it is disputed (No in the case of DNK/GRL, yes in the case of XKX and SER).

Most recent list is here: 
https://github.com/wmgeolab/geoBoundaryBot/blob/main/dta/iso_3166_1_alpha_3.csv

**Comment by joelorentz** [comment]
I see that the above listed countries have been added to the list of ISO codes.
However, the global ADMO files seems to still ignore these countries if I am not mistaken? E.g. there is no shape included in the geoBoundariesCGAZ_ADM.geojson that indicates the Isle of Man - instead the region is included in the shape of the United Kingdom.

Any plans to change this?
