### ISSUE TITLE
unresponsive or no data URLs in HPSCGS dataset 

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1144]
### What is the expected behavior?
I expected these urls to have data since they are in the api, but they dont.
https://geoboundaries.org/data/geoBoundariesHPSCGS-3_0_0/NIU/ADM0/geoBoundariesHPSCGS-3_0_0-NIU-ADM0.geojson
https://geoboundaries.org/data/geoBoundariesHPSCGS-3_0_0/PSE/ADM0/geoBoundariesHPSCGS-3_0_0-PSE-ADM0.geojson

https://geoboundaries.org/data/geoBoundariesHPSCGS-3_0_0/NIU/ADM1/geoBoundariesHPSCGS-3_0_0-NIU-ADM1.geojson
https://geoboundaries.org/data/geoBoundariesHPSCGS-3_0_0/PSE/ADM1/geoBoundariesHPSCGS-3_0_0-PSE-ADM1.geojson

https://geoboundaries.org/data/geoBoundariesHPSCGS-3_0_0/PSE/ADM2/geoBoundariesHPSCGS-3_0_0-PSE-ADM2.geojson
### Any possible solutions?

[ ] I'll work on a PR for this!

**Comment by DanRunfola** [comment]
I won't be fixing this for 3.0, but definitely a bug and thanks for raising.  This will be fixed when we push to 4.0, as we're updating the back-end of the API to operate with the github repository, so the way the DB responds will be much (much, much) more resilient than what we have today.
