### ISSUE TITLE
[BOUNDARY ERRATA] AUS ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1169]
**Describe the Error**
AUS ADM2 has a topological error we can't algorithmically fix

**Screenshots**
![image](https://user-images.githubusercontent.com/7882645/115287201-fadf6500-a11d-11eb-85cd-71b7b2172127.png)

There is a small gap between boundaries located roughly at where the circle exists (thanks to Max at the WFP for putting together this image).

**Comment by hadleyday** [comment]
https://github.com/wmgeolab/geoBoundaries/pull/1581 - did not link the issue to the PR
