### ISSUE TITLE
FJI-ADM0-3_0_0-B1

### ISSUE THREAD

**Issue by gabriellaIO** [wmgeolab/geoBoundaries#1216]
### What is the expected behavior?
The extent of this shape in EPSG:4326 should not go beyond 180.0 degrees longitude. 

### What is the actual behavior?  The more detail the better.
The extent of the shape in QGIS is 

Extent | -180.0000000000000000,-20.6683418615518981 : 180.0000000000001705,-12.4795315999999996
-- | --

(Note that it is greater than 180.0 degrees) 

### Other notes on how to reproduce the issue?
Download the geoBoundariesCGAZ_ADM0.geojson, open the file in QGIS, select the Fiji (FJI-ADM0-3_0_0-B1) polygon, export, "save selected feature as", check the extent of the new shape for Fiji. It will be the same as shown above. 

### Any possible solutions?
Use the Extract/clip by extent tool in QGIS to edit the shape to clip the longitude to 180.0 degrees.

**Comment by taraamcl** [comment]
having a lot of issues with this file, I've tried to multiple times but it keeps getting distorted. I'm really not sure how to fix it. The projection used on Humdata is different and I think the issue is coming from me trying to save it as WGS84
