### ISSUE TITLE
Is there more documentation on the code assignment philosophy of the project?

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1239]
There are a number (248) of cases in the Admin1 layer where for ShapeISO there is either no code (12), the word “none” (191), simply the three letter ISO country code (44), and one case with a _ used for a code.

@DanRunfola

**Comment by DanRunfola** [comment]
Hi Lee,

This is unstandardized in 3.0; in 4.0 it will either be present or
"Unknown".

In terms of philosophy - we guarantee ISO codes at ADM0, and do best-effort
at lower levels.

Dan

**Comment by leeberryman** [comment]
Thanks @DanRunfola in 4.0 will more of the ADM0 instances where there are ISO codes be assigned to their shapes even when they aren't countries?  I'm thinking in particular everything that ends of being coded as FRA currently, but there are many other instances of this.

**Comment by DanRunfola** [comment]
I'm not quite sure of the question - I assume you're referring to
territories?  Right now, we don't have a systematic inclusion of
territories, but we're definitely working towards it.  The goal is to have
two fields - the ISO of the country, and then the ISO of the territory, in
cases where it's relevant.  Right now it's a little bit arbitrary - i.e.,
Greenland gets its own ISO.

Technically, we hope to implement this as an additional column in our
master ISO tracking CSV, which includes a "countryISO".  So, the row for
GRL would have "DNK" for the countryISO column.  A country like MEX would
have MEX for the countryISO column.  That way we can maintain individual
shapes for territories, but still let users roll them into different
administrative units later (esp. in the case of conflicted territories).

**Comment by leeberryman** [comment]
@DanRunfola yes thats what I mean.  Your solution makes sense, is this a post v4 implementation?  I noticed in v3 many of the places that have conflicted views ended up being absent from the map, meaning they had no polygon coverage.

**Comment by DanRunfola** [comment]
Yes, right now conflicted regions may be absent.  I'd say more of a 4.5
target for us (by the end of the year) is to have complete territory
coverage.  For 4.0 we're really focused on getting the country ISOs covered
and all of our processes moved over to github.
