### ISSUE TITLE
gBOPEN - ATA ADM 1

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#125]
We need to determine if Antarctica has ADM 1.

**Comment by sgmurphy216** [comment]
ATA technically does have an ADM1; there are a total of 8 territorial claims from seven nations. Existing polygon data for ATA ADM1 is sparse, rarely uses WGS84 (polygon treatment at the poles is strange, most use a polar stereographic projection placing ATA centrally), and most existing datasets show territorial claims by using lines separating ATA from the South Pole, partitioning areas like slices of a pie as opposed to creating full polygons. Completion of ATA_adm1 would likely need to be done manually if we were to keep it in wgs84- happy to start.

So what do we think? WGS or polar stereo?

**Comment by DanRunfola** [comment]
Hm - this is an interesting question.  ATA is likely to be very, very rarely used, but I think is worth including.

Let's try it in WGS84 for consistency, but I recognize that this is going to be suboptimal.  Just not sure what a better choice is.
