### ISSUE TITLE
gBOpen - MDV ADM 2

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#126]
We may have a raw file of ADM 2 for the Maldives that needs to be processed. If not, we'll need to search for a new one.

**Comment by slfuhrig** [comment]
Check the raw folder first to see if there is an ADM 2 shapefile with an open license there. If not, we'll need to find a new file.

**Comment by slfuhrig** [comment]
It looks like we need to find a new file, as no suitable candidates are listed in our raw data.

**Comment by leeberryman** [comment]
I have a candidate.  So ADM2 would be considered the islands and ADM1 is the atolls correct?
