### ISSUE TITLE
shapeID = ECU-ADM1-1590546715-B23

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1288]
### What is the expected behavior?
Here is one minor error in the 3_0_0 GeoBoundary data. In ADM1, Ecuador, for shapeID = ECU-ADM1-1590546715-B23, shapeName = SANTO DOMINGO DE LOS TSACHILAS the shapeISO should be EC-SD. That would match the ISO code. Currently there is an underscore is used instead of a dash (EC_SD). This is the only case of an underscore being used in the whole world, which looks like a mistake.

### Any possible solutions?

[ ] I'll work on a PR for this!

**Comment by DanRunfola** [comment]
This should now be corrected in GB 4.0.
