### ISSUE TITLE
gBOPEN - ETH ADM 4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#129]
Ethiopia's ADM 4, kebele, need to be included in our dataset. There are approximately 15,000 such features.

**Comment by slfuhrig** [comment]
It's nearly impossible to find this shapefile, so it's being moved to 5.0

**Comment by rmbiddle** [comment]
https://ethiopia.africageoportal.com/datasets/5fbc3698295e4a97a015219849ed35ad_0?geometry=7.105%2C1.543%2C73.858%2C16.683

Source with shapefile however no license is provided

**Comment by DanRunfola** [comment]
Closing stale issues for ADM3 and below.
