### ISSUE TITLE
gBOPEN - RUS ADM 3

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#132]
Our existing ADM 3 for Russia has some problems that need to be revised, or we will need to find a new file.

**Comment by slfuhrig** [comment]
Additionally, RUS ADM 3 does not have an entry in gB OPEN metadata. So, we need to check the raw records to find the information to add to the gB OPEN metadata csv. If no records are found, we will need a new shapefile. Considering the existing problems with our current shapefile, it may make more sense to see if we can find a new one.

**Comment by slfuhrig** [comment]
We also need to review the ADM structure and hierarchy of Russia as a whole to make sure what we have is correct.

**Comment by kpupkiewicz** [comment]
Organization for Russia is confirmed to be 
Adm1 - federal subjects (85)
	includes oblasts (46), republics (22), krais (9), autonomous okrugs (4), autonomous oblasts (1), federal cities (3) 
Adm2 - raions (2027) and cities of federal subject significance (561)
	also includes divisions of Federal cities; Moscow (12), St. Petersburg (18), Sevastopol (4) 
Adm3 - towns of district significance (416); urban-type settlements of district significance (767); selsoviets (15002)
Any data used has to be recent enough to include Crimea. ADM3 data seems rare - leaving until Spring 2021 semester.

**Comment by slfuhrig** [comment]
It's proving very difficult to find this boundary. Will focus on other issues for 4.0.

**Comment by DanRunfola** [comment]
Closing stale issues for ADM3 and below.
