### ISSUE TITLE
gBOPEN - MMR ADM 4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#133]
We have a shapefile with topology issues that will need to be fixed in mapshaper, or we will need a new file.

**Comment by slfuhrig** [comment]
It appears that we have a shapefile in gB OPEN, but it is not listed in metadata, so we need to find the metadata information and update the gB OPEN metadata csv.

**Comment by dfornatora** [comment]
Only source that seems to be available is under the MIMU license, which can not be used for gbOpen. (http://themimu.info/license/)

**Comment by DanRunfola** [comment]
I'm going to remove what we have from our source folder for now, for the sake of closing this for 4.0.

We'll can always retrieve it from the archive if we need to revisit.
