### ISSUE TITLE
LBY ADM1 and ADM2

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1330]
A few thoughts and comments on LBY.  It appears that there is a province layer (3 provinces) that should be the ADM1 in LBY rather than the districts (22 districts) that are currently GeoBoundaries ADM2.

https://data.humdata.org/dataset/fd9fb749-5b68-4942-b5f9-115f20b5c00e/resource/86a02bfa-82c7-48ab-9e67-61fed673e296/download/lby_adm_unosat_lbsc_20180507.gdb.zip

Is the following license an accepted license in GeoBoundaries?
[Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/dataset/admin-boundaries-villages-libya-cods)

This seems to indicate an additional layer of boundaries as well:  https://en.wikipedia.org/wiki/Baladiyat_of_Libya
https://upload.wikimedia.org/wikipedia/commons/6/62/Libya_municipalities.png

**Comment by DanRunfola** [comment]
@leeberryman Yes - CC Attribution for IO is accepted - right now we specifically take "Creative Commons Attribution 4.0 International (CC BY 4.0)"

@sgmurphy216 Could you have someone do a deep dive on LBY regarding this at some point over the summer?

**Comment by sgmurphy216** [comment]
@DanRunfola @leeberryman Absolutely! 
Preliminary research reflects what Lee is saying- ADM1 should contain three provinces. Historically, ADM2 would contain 'governorates', further subdivided into 'districts'.
It appears that while the ADM3, 'districts', have been demarcated, ADM2 'governorates' have not.
We'll do some more research on this in the coming weeks, but corrections will be forthcoming. Great catch, Lee!

**Comment by kpupkiewicz** [comment]
Current situation in Libya is quite complicated. The country has been in a civil war for quite some time, so state-endorsed sub-national boundary structures aren’t really an option. 
For clarity’s sake I’ll explain the names of the boundary levels here. Our point of contention is the 3 provinces at the proposed ADM1 level. The levels beneath that would then be Shabiyat at ADM2, Baladiya at ADM3, and Muhulla at ADM4. 
The provider for most data in the region is the International Organization for Migration (IOM)’s Displacement Tracking Matrix. For their organization’s purposes, having the 3 provinces is useful to describe broad trends in the country’s migration. So rather arbitrarily, they publish their data including this ADM1. Their data is the dataset Lee linked in the original post - here is the URL for it from HDX https://data.humdata.org/dataset/admin-boundaries-villages-libya-cods. 
Libya’s most recent functioning constitution (from approx. 2007??), however, does not include this boundary level. It instead moves the Shabiyat up to ADM1. Data from organizations that are not working with IOM typically use the Shabiyat as ADM1, especially within the last year in a lot of research published on COVID-19. 
So, there are arguments for both including the provinces and disincluding the provinces. I’m inclined to include them I think ¯\_(ツ)_/¯

Also, any polygon data for Baladiya or Muhulla (the more granular levels) are proving almost impossible to find. Almost everything I happen to find is just point data. Arrgh.

**Comment by DanRunfola** [comment]
Keeping with "we seek to represent countries as they represent themselves", I think that we need to eschew the use of the IOM data, and defer to the Libyan definitions, even if they aren't operationally being used.

One thing we might do is include the IOM cases in our gbHumanitarian release, but not gbOpen.  How does that sound @kpupkiewicz @sgmurphy216 ?

**Comment by sgmurphy216** [comment]
Sounds good to me! Will get on that ASAP.
