### ISSUE TITLE
gBOPEN - MDG ADM 3-4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#134]
We have Madagascar ADM 3-4 shapefiles, but they do not appear to be listed in our metadata sheet. This needs to be corrected.

**Comment by hannahslevin** [comment]
https://data.humdata.org/dataset/madagascar-administrative-level-0-4-boundaries

**Comment by slfuhrig** [comment]
We need to update our shapefiles for ADM3 and ADM4 with the link Hannah found.
