### ISSUE TITLE
France - Open Gov License 

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#1341]
**Describe the Error**
FRA_ADM5 brought up the issue of the French open license (Open License Etalab) which is compatible with other licenses such as Open Government License of the United Kingdom, Open Data Commons Attribution (OCD-BY), and Creative Commons Attribution 2.0 (CC-BY-2.0) - this should be considered for the list of acceptable licenses for geoBoundaries.

**Screenshots**
If applicable, add screenshots or images to help explain your problem.

**Additional context**
https://fr.wikipedia.org/wiki/Licence_ouverte_(%C3%89tat_fran%C3%A7ais)#:~:text=La%20Licence%20ouverte%20%2F%20Open%20Licence,pr%C3%A9sent%C3%A9e%20le%2018%20octobre%202011

**Comment by lydiatroup** [comment]
closing this bc this license type is now compatible with the bot
