### ISSUE TITLE
gBOPEN - TCD ADM3

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#144]
We need to add Chad's ADM 3 (subprefectures).

**Comment by hannahslevin** [comment]
https://maps.princeton.edu/catalog/stanford-tv546gt8718
potential shapefile for TCD adm 3.  The metadata says that the file is public domain and there are no restrictions for usage.

**Comment by hannahslevin** [comment]
https://purl.stanford.edu/tv546gt8718

**Comment by DanRunfola** [comment]
Closing stale issues for ADM3 and below.
