### ISSUE TITLE
[BOUNDARY ERRATA] Lithuania ADM3

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1443]
If we (geoBoundaries) digitized Lithuania ADM3 from a public domain image, we should be the source for it.  A wiki entry should be made describing what we did and why we are listed as the sources.

**Comment by sgmurphy216** [comment]
[LTU_ADM3_Issues.pdf](https://github.com/wmgeolab/geoBoundaries/files/6600380/LTU_ADM3_Issues.pdf)
Hey- we may want to repair this source or scrap it and find a new one for a few reasons:

- Out-of-date attribute conventions
- Encoding error in shapeName field (poly names are indecipherable)
- Small hole over a town called Molėtai
- Incorrect number of features (544 in file, 546 through [research](https://usa.mfa.lt/usa/en/welcome-to-lithuania/visit-lithuania))

Will work on finding a new source.

**Comment by 11helenab** [comment]
Closed, Pull request #3926
