### ISSUE TITLE
gB OPEN - Missing Layers

### ISSUE THREAD

**Issue by maxmalynowsky** [wmgeolab/geoBoundaries#1456]
Hey guys, opening up my first issue, let me know if this format works for you! (single overarching theme with checkboxes for affected layers) The following are some layers that I noticed were missing from `releaseData/gbOpen`. There are two criteria I had for a missing layer. The first was if something like an ADM2 was present, but ADM1 or ADM0 were absent. The second case for a missing layer was for example, if layers up to ADM2 were available on the main branch (looks ok by itself), but an ADM3 existed in the v3 release (indicating a loss in admin levels compared to the previous release).

- [x] AFG_ADM0
- [x] AFG_ADM2
- [x] AGO_ADM3
- [x] BGD_ADM3
- [x] BGD_ADM4
- [x] KGZ_ADM2
- [x] KNA_ADM1
- [x] LKA_ADM3
- [x] NER_ADM0
- [x] NER_ADM2
- [x] NRU_ADM1
- [x] NRU_ADM2
- [ ] OMN_ADM2
- [x] PER_ADM2
- [x] PHL_ADM0
- [ ] PNG_ADM3
- [x] PRK_ADM2
- [x] PSE_ADM2
- [x] SDN_ADM0
- [x] SDN_ADM2
- [x] SEN_ADM0
- [x] SEN_ADM1
- [x] SEN_ADM2
- [x] SEN_ADM3
- [x] SLE_ADM0
- [x] SLE_ADM1
- [x] SLE_ADM2
- [x] SLE_ADM3
- [x] TUR_ADM0
- [x] TUR_ADM1
- [x] TUR_ADM2
- [x] TZA_ADM2
- [x] UKR_ADM2
- [x] URY_ADM2
- [x] ZAF_ADM0
- [x] ZAF_ADM1
- [x] ZAF_ADM2
- [x] ZAF_ADM3
- [x] ZAF_ADM4

**Comment by sgmurphy216** [comment]
Hey @maxmalynowsky ! Thanks for the issue- we're looking into this. Will update you as we progress.

**Comment by DanRunfola** [comment]
As an aside, we're also hoping to get a more complete territorial coverage looking beyond the 4.0 "release" later this summer.

**Comment by DanRunfola** [comment]
@maxmalynowsky @sgmurphy216 As we've created individual issues for each of these, I think we're safe to close this issue now.  Correct?

**Comment by DanRunfola** [comment]
Just confirming, this can now be closed out.  A few issues remain, but they're being tracked in individual tickets.
