### ISSUE TITLE
[BOUNDARY ERRATA] gB OPEN - Partial Layers

### ISSUE THREAD

**Issue by maxmalynowsky** [wmgeolab/geoBoundaries#1457]
Hey all, after the missing layer issue I just posted, this is the second overarching theme I came across that affected quite a few layers. For these layers, I found that they were missing admin units over land that don't cover the ADM0, not counting holes over water bodies as those are assumed to be intentional. My guess is that these are polygons being dropped by the simplification process, I haven't checked the sources to see if they are present there. I've attached a screenshot of each layer, with the area of interest circled in red. All layers were freshly pulled from `main/releaseData/gbOpen` today before creating the screenshots below to make sure they're still missing, since I saw that many of the previous partial layers I found a few weeks ago have already been fixed, good job with that!

- [x] AUS_ADM2
![aus_adm2](https://user-images.githubusercontent.com/4202166/121092148-6a530600-c7eb-11eb-8696-3a1786aaa4e4.png)

- [ ] BDI_ADM3
![bdi_adm3](https://user-images.githubusercontent.com/4202166/121093276-177a4e00-c7ed-11eb-83ac-13150f0495ad.png)

- [ ] BHS_ADM1
![bhs_adm1](https://user-images.githubusercontent.com/4202166/121093313-26f99700-c7ed-11eb-9211-5b17ef61dc8e.png)

- [ ] BLR_ADM2
![blr_adm2](https://user-images.githubusercontent.com/4202166/121093346-3678e000-c7ed-11eb-9485-32f3428804b4.png)

- [ ] BRA_ADM2
![bra_adm2](https://user-images.githubusercontent.com/4202166/121093398-45f82900-c7ed-11eb-9c36-e6831e19b2b8.png)

- [x] CHE_ADM2
![che_adm2](https://user-images.githubusercontent.com/4202166/121093422-4db7cd80-c7ed-11eb-8557-45b89fd969e8.png)

- [ ] CHN_ADM3
![chn_adm3](https://user-images.githubusercontent.com/4202166/121093474-60320700-c7ed-11eb-9ae2-2f243c8aa398.png)

- [ ] CPV_ADM2
![cpv_adm2](https://user-images.githubusercontent.com/4202166/121093488-66c07e80-c7ed-11eb-81be-28df0cc71484.png)

- [ ] CRI_ADM3
![cri_adm3](https://user-images.githubusercontent.com/4202166/121093503-6b853280-c7ed-11eb-9d27-ca1647771732.png)

- [ ] CUB_ADM2
![cub_adm2](https://user-images.githubusercontent.com/4202166/121093518-7049e680-c7ed-11eb-9188-80cd24cacaac.png)

- [ ] CYP_ADM2
![cyp_adm2](https://user-images.githubusercontent.com/4202166/121093532-75a73100-c7ed-11eb-9f81-032d8963a54b.png)

- [ ] CZE_ADM4
![cze_adm4](https://user-images.githubusercontent.com/4202166/121093543-79d34e80-c7ed-11eb-9972-2eb57f43d385.png)

- [ ] FIN_ADM2
![fin_adm2](https://user-images.githubusercontent.com/4202166/121093563-8061c600-c7ed-11eb-8d87-1c01155c5e91.png)

- [ ] FIN_ADM3
![fin_adm3](https://user-images.githubusercontent.com/4202166/121093575-85267a00-c7ed-11eb-81c6-5e9df5ecf263.png)

- [x] FRA_ADM4
![fra_adm4](https://user-images.githubusercontent.com/4202166/121093594-89eb2e00-c7ed-11eb-8714-0e1a97783636.png)

- [x] GTM_ADM2
![gtm_adm2](https://user-images.githubusercontent.com/4202166/121093612-91aad280-c7ed-11eb-9dc2-f25e7c1c19dd.png)

- [ ] HND_ADM2
![hnd_adm2](https://user-images.githubusercontent.com/4202166/121093638-97081d00-c7ed-11eb-9ae9-322e0a82d107.png)

- [x] IRN_ADM3
![irn_adm3](https://user-images.githubusercontent.com/4202166/121093650-9b343a80-c7ed-11eb-85e4-1315b4cb891b.png)

- [x] IRN_ADM4
![irn_adm4](https://user-images.githubusercontent.com/4202166/121093664-9ff8ee80-c7ed-11eb-90f8-485a018e730a.png)

- [ ] ISR_ADM2
![isr_adm2](https://user-images.githubusercontent.com/4202166/121093676-a5eecf80-c7ed-11eb-99c8-93903ea295f5.png)

- [ ] KWT_ADM2
![kwt_adm2](https://user-images.githubusercontent.com/4202166/121093687-aa1aed00-c7ed-11eb-96be-04c93dca2acc.png)

- [ ] LVA_ADM2
![lva_adm2](https://user-images.githubusercontent.com/4202166/121093694-adae7400-c7ed-11eb-8688-14a16702f4de.png)

- [ ] MDV_ADM0
![mdv_adm0](https://user-images.githubusercontent.com/4202166/121093710-b606af00-c7ed-11eb-8a7d-c6492897dbb8.png)

- [ ] MDV_ADM1
![mdv_adm1](https://user-images.githubusercontent.com/4202166/121093727-ba32cc80-c7ed-11eb-85e2-373ec2877101.png)

- [x] MNG_ADM2
![mng_adm2](https://user-images.githubusercontent.com/4202166/121093737-bdc65380-c7ed-11eb-9d9a-fb498dd4d9d3.png)

- [x] PAN_ADM3
![pan_adm3](https://user-images.githubusercontent.com/4202166/121093752-c3239e00-c7ed-11eb-87fb-15a177ae589c.png)

- [x] POL_ADM2
![pol_adm2](https://user-images.githubusercontent.com/4202166/121093758-c61e8e80-c7ed-11eb-9d81-f9f995d0db5c.png)

- [x] RUS_ADM2
![rus_adm2](https://user-images.githubusercontent.com/4202166/121093768-cb7bd900-c7ed-11eb-9fd8-95382b979b42.png)

- [x] SVK_ADM3
![svk_adm3](https://user-images.githubusercontent.com/4202166/121093777-cf0f6000-c7ed-11eb-982a-bb5ea699f307.png)

- [x] SVK_ADM4
![svk_adm4](https://user-images.githubusercontent.com/4202166/121093786-d5054100-c7ed-11eb-8f5d-fc50b1aa1016.png)

- [x] TON_ADM2
![ton_adm2](https://user-images.githubusercontent.com/4202166/121093795-dafb2200-c7ed-11eb-8837-7112e40f4238.png)

- [x] TUN_ADM3
![tun_adm3](https://user-images.githubusercontent.com/4202166/121093805-de8ea900-c7ed-11eb-84be-d6b9130364b4.png)

- [x] TUV_ADM2
![tuv_adm2](https://user-images.githubusercontent.com/4202166/121093820-e3535d00-c7ed-11eb-9c8a-0d0d0b90e0ce.png)

- [x] TUV_ADM3
![tuv_adm3](https://user-images.githubusercontent.com/4202166/121093827-e77f7a80-c7ed-11eb-8de1-4b244a73bfb8.png)

**Comment by DanRunfola** [comment]
Many, many thanks for this deep dive.  We'll aim to have these fixes in for 4.0.

**Comment by DanRunfola** [comment]
@sgmurphy216 Did we create individual issues for all of these already?  I am not certain, but know I've seen a number of these boundaries cross the PR wire in the last couple of weeks so suspect we did in at least some cases.

**Comment by DanRunfola** [comment]
We have created individual tickets for each of these issues, so closing this master ticket out for now.
