### ISSUE TITLE
gB Authoritative NZL

### ISSUE THREAD

**Issue by sgmurphy216** [wmgeolab/geoBoundaries#1478]
Expansion of gB Authoritative; data at https://www.unsalb.org/data/nzl

*Metadata and license at https://www.unsalb.org/sites/default/files/wysiwyg_uploads/docs_uploads/SALB_DataSpecifications_v2.0_20210601.pdf
List license type as:
UN SALB Data License

**Comment by carolinamonrivera** [comment]
@sgmurphy216 License needs to be added to the list for all checks to pass.

**Comment by DanRunfola** [comment]
https://github.com/wmgeolab/geoBoundaries/pull/1533
