### ISSUE TITLE
gB Authoritative QAT

### ISSUE THREAD

**Issue by sgmurphy216** [wmgeolab/geoBoundaries#1480]
Expansion of gB Authoritative; data at https://www.unsalb.org/data/qat

*Metadata and license at https://www.unsalb.org/sites/default/files/wysiwyg_uploads/docs_uploads/SALB_DataSpecifications_v2.0_20210601.pdf
List license type as:
UN SALB Data License

**Comment by dfornatora** [comment]
The UN SALB link does not have validated data in form of a shapefile. It has a link to the country's GIS portal, but it does not seem like there is downloadable data.
