### ISSUE TITLE
gB Authoritative ZMB

### ISSUE THREAD

**Issue by sgmurphy216** [wmgeolab/geoBoundaries#1484]
Expansion of gB Authoritative; data at https://www.unsalb.org/data/zmb

*Metadata and license at https://www.unsalb.org/sites/default/files/wysiwyg_uploads/docs_uploads/SALB_DataSpecifications_v2.0_20210601.pdf
List license type as:
UN SALB Data License

**Comment by DanRunfola** [comment]
Closed by #1510 (ADM1, 2) and #1484 (ADM0)
