### ISSUE TITLE
COD_ADM2 gbOpen

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#1523]
Our current COD_ADM2 has 48 features. Upon further research, this is not the correct number of features needed for the DRC. More research is needed to find a more accurate shapefile to represent ADM2.

**Comment by dfornatora** [comment]
ADM2 file we currently have is an incorrect version of ADM1. ADM3 file is a version of ADM2. ADM3 file needs to be removed. Uploading a new file for ADM2
