### ISSUE TITLE
[BOUNDARY ERRATA] BGD-ADM3 Metadata

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1547]
In gbOpen, there is an issue with BGD-ADM3.  While I can't look into it right now, I think the meta.txt in the BGD-ADM3 zip file incorrectly is specifying the layer as ADM2, instead of ADM3.

For this issue, if someone could please take a look at both BGD-ADM2 and BGD-ADM3 and make corrections as may be needed.  Just want to make sure nothing is swapped!

Raised in the auto-build:
https://github.com/wmgeolab/geoBoundaries/runs/2966163111?check_suite_focus=true

**Comment by dfornatora** [comment]
This issue was corrected with issue #1462. The boundary type was corrected to ADM3 in the metadata.
