### ISSUE TITLE
[BOUNDARY ERRATA] CIV ADm2 / ADM0

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1548]
**Describe the Error**
In the metadata, CIV_ADM2.zip in gbOpen has "ADM0" as the boundary type.  Need someone to take a pass and confirm what's right/wrong on this one.

**Comment by dorianvmiller** [comment]
@DanRunfola I just downloaded the .zip for ADM0 and ADM2 from github and everything looks fine to me - both layers looked correct but also had the correct boundary type listed. Let me know if I missed anything!

**Comment by DanRunfola** [comment]
Ack, I'm sorry - this was Humanitarian.  Looks like it's the CIV_ADM2.zip at fault.

https://github.com/wmgeolab/geoBoundaries/runs/2967598909?check_suite_focus=true#step:4:29

**Comment by dorianvmiller** [comment]
I see the problem now - I'll fix this and get a PR together to update the ADM2!
