### ISSUE TITLE
[BOUNDARY ERRATA] gbHumanitarian CIV ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1559]
**Describe the Error**
There are some odd metadata errors in boundary source 1 - looks like an encoding error - for CIV ADM2.

**Comment by dfornatora** [comment]
@DanRunfola The source (Humdata) for this file has changed their license for this data to Creative Commons Attribution 3.0 Intergovernmental Organisations (CC BY 3.0 IGO) instead of Other - Humanitarian. Do we still want to keep this in gbHumanitarian? I believe this also applies to ADM0, 1, and 3.

**Comment by DanRunfola** [comment]
Triple check this license - what's the underlying source?  I.e., is it GADM?  There is a lot of confusion re: data providence on HDX right now, so I want to be careful.

**Comment by dfornatora** [comment]
@DanRunfola HDX's source is Comité National de Télédétection et d'Information Géographique (CNTIG), which is a government committee in Côte d'Ivoire.

**Comment by DanRunfola** [comment]
Ok - got it.  Can we go to that actual source and see if they have the
boundary available?

In general, I don't want to rely on HDX for license information; we'll be
deprecating that eventually.

**Comment by dfornatora** [comment]
@DanRunfola Looking into their website, I do not believe they provide free data to download. Under their data tab they say that they "develop geospatial data and content at the request of various organizations" and in another place they say their main activity is the "sale of geospatial solutions." They do have a list of data they have available, and administrative boundaries are part of it, but it is not downloadable.

**Comment by DanRunfola** [comment]
Ok, got it.

Let's stick with our previous license, then, as we're using the same data.
We can seek to update it later.

Dan

**Comment by dfornatora** [comment]
@DanRunfola Ok. Looking back at the source data, Dorian submitted a file for CIV_ADM2 that might have corrected the encoding error. An adm0 file was previously submitted for adm2, but now in the source folder it is the correct adm2 file.
