### ISSUE TITLE
gBOPEN PHL ADM 3

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#156]
Our existing ADM is authoritative and humanitarian.

**Comment by DanRunfola** [comment]
To clarify - we need to find a new gbOpen for this.

**Comment by lydiatroup** [comment]
Found this shapefile: https://web.archive.org/web/20190618021200/http://philgis.org/country-barangay/country-barangays-file

But the website no longer exists, and unknown usage information
