### ISSUE TITLE
gbOPEN PHL ADM 0

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#157]
Our existing ADM is authoritative and humanitarian (note quality issues mentioned in previous issue).

**Comment by DanRunfola** [comment]
What's the action item on this issue?

Just trying to clarify when it can be closed out.

**Comment by slfuhrig** [comment]
We need to find an open license ADM 0 for PHL in addition to what we have for humanitarian and authoritative.
