### ISSUE TITLE
Some boundaries don't have the standard 'shapeName' feature property

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1612]
**Describe the Error**
I came across gbOpen Afghanistan (all admin levels) which don't have the typical feature name-property 'shapeName', instead the name is stored in a 'PROV_34_NA' property. I'm pretty sure I've noticed this with some other boundaries too, and it should be easy enough to loop through all files to see which ones have or don't have the 'shapeName' feature property. See e.g. below: 

https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/AFG/ADM1/geoBoundaries-AFG-ADM1.topojson

**Comment by DanRunfola** [comment]
This was corrected a bit ago by a new AFG dataset.  Closing for now.
