### ISSUE TITLE
[BOUNDARY ERRATA] Existance of Bahrain (BHR) ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1617]
We need to confirm if BHR ADM2 exists or not - if it doesn't, we need a wiki entry to that effect.

**Comment by rsritchey** [comment]
Bahrain's ADM2 level is divided into constituencies. Meaning BHR ADM2 exists, but a shape file is yet to be located.

**Comment by leeberryman** [comment]
@DanRunfola Where is the wiki?

**Comment by sgmurphy216** [comment]
> @DanRunfola Where is the wiki?

Hey Lee!

If you're asking where on the site it's located, you can access the wiki through the top ribbon or at https://github.com/wmgeolab/geoBoundaries/wiki . However, if asking for the wiki page on BHR_ADM2 specifically, we will be opening an issue attempting to locate a data source and won't need a page for it unless it can't be found.

**Comment by leeberryman** [comment]
Thanks @sgmurphy216 I was asking in general where all of these wikis are.  Great work!  Excited to see v4 release!!

**Comment by DanRunfola** [comment]
Closing as duplicate of https://github.com/wmgeolab/geoBoundaries/issues/1643
