### ISSUE TITLE
[BOUNDARY ERRATA] JPN ADM0

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1619]
Something is breaking the JPN ADM0 build, silently. Can someone please download the zip file, check the metadata and re-upload?

**Comment by DanRunfola** [comment]
This isn't the data - JPN is fine.  Just the build script!  Sorry.

**Comment by rsritchey** [comment]
Oh lol. It was missing the license.png though so I am gonna resubmit

**Comment by DanRunfola** [comment]
Aha, nice.  Thank you.
