### ISSUE TITLE
[BOUNDARY ERRATA]  WSM ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1632]
We need to confirm if Samoa (WSM) ADM2 exists, and if not update the wiki.

**Comment by MichaelR-geoLab** [comment]
Samoa appears to have up to an ADM3 level. itūmālō (political districts), Electoral constituency, and village.

**Comment by DanRunfola** [comment]
Ok - for 4.0, let's add this to our to-do and see if we can find the ADM2.  ADM3 is a little less important, but great if it pops up somewhere.

**Comment by kpupkiewicz** [comment]
@DanRunfola @MichaelR-geoLab Already have ADM2 covered! https://github.com/wmgeolab/geoBoundaries/pull/1592 
I didn't do a deep enough dive to know exactly how accurate these boundaries are, but the source I used appears to go down to ADM3. https://pacificdata.org/data/dataset/2011_wsm_phc_admin_boundaries
