### ISSUE TITLE
[BOUNDARY ERRATA] MDA ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1633]
We need to check if the Republic of Moldova has a ADM2, and if not update the wiki.

**Comment by MichaelR-geoLab** [comment]
Moldova ADM2 exists but I could not find a Shapefile for it

**Comment by DanRunfola** [comment]
Ok - I'm going to leave it as a red X in our dataset for 4.0, and we'll try to get this one in 5.0.

**Comment by DanRunfola** [comment]
This isn't QUITE going to make it into 4.0.  We'll add it in very shortly after release, most likely, depending on how the grueling geocoding is going :)))

**Comment by DanRunfola** [comment]
Closing as duplicate.
