### ISSUE TITLE
[BOUNDARY ERRATA] MLT ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1635]
We need to confirm if Malta has an ADM2, and if not update the wiki.

**Comment by rsritchey** [comment]
According to wikipedia, Malta only has one administrative tier.

**Comment by rsritchey** [comment]
Correction: It appears that Malta further divides into councils

**Comment by DanRunfola** [comment]
Ok - let's dig a little further on this, and confirm if we need (or not) to get a shapefile.

**Comment by kpupkiewicz** [comment]
What we currently have in gB is correct - there is only one subdivision for Malta (which is the Il-Kunsilli Lokali / local council). Making a wiki entry now.
