### ISSUE TITLE
gBOPEN QAT ADM 0 metadata 

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#164]
We have a gB OPEN shapefile for QAT ADM 0, but no metadata information is listed. So, we need to check the raw records to find the information to add to the gB OPEN metadata csv. If no records are found, we will need a new shapefile.

**Comment by hadleyday** [comment]
Possible Links to check out 
https://osm-boundaries.com/Download/Submit?apiKey=8ab9916ffb7ae463e47ebf5c7d87e3fc&db=osm20200907&osmIds=-305095&recursive&landOnly
http://goleaddog.com/gis-map/middle-east/qatar/
https://www.unsalb.org/data/qat
