### ISSUE TITLE
gbOpen BHR ADM2

### ISSUE THREAD

**Issue by rsritchey** [wmgeolab/geoBoundaries#1643]
According to Statoids (http://www.statoids.com/ubh.html) and wikipedia (https://en.wikipedia.org/wiki/Governorates_of_Bahrain), Bahrain ADM2 exists and their canonical boundary name is called constituencies. Please locate a shape file for this and upload to gbOpen.

**Comment by dfornatora** [comment]
Constituencies of Bahrain appear to only be for electoral purposes, not administrative zones, so an ADM2 should not be listed. Wiki has been created explaining.
