### ISSUE TITLE
[BOUNDARY ERRATA] AFG ADM0 gbOpen

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1648]
The source for ADM0 gbOpen is a url - we need to put the *name* of the source in the source field, and hte URL only in the url field :)

**Comment by dfornatora** [comment]
Note in meta said that ADM0 was made by dissolving boundaries, so changed Source 1 to geoBoundaries and Source 2 to the name of source (not the url). Will make a wiki explaining why source 1 is geoBoundaries

**Comment by sgmurphy216** [comment]
> Note in meta said that ADM0 was made by dissolving boundaries, so changed Source 1 to geoBoundaries and Source 2 to the name of source (not the url). Will make a wiki explaining why source 1 is geoBoundaries

Great work Dominic!
