### ISSUE TITLE
gB OPEN FRA ADM 5 metadata

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#166]
We have a gB OPEN shapefile for FRA ADM 5, but no metadata information is listed. So, we need to check the raw records to find the information to add to the gB OPEN metadata csv. If no records are found, we will need a new shapefile.

**Comment by sylviashea1** [comment]
May have been closed. Issue seems to be open, not sure what issue this is tied to currently.

**Comment by slfuhrig** [comment]
Dan will push since the file is so large

**Comment by DanRunfola** [comment]
Closed by https://github.com/wmgeolab/geoBoundaries/pull/1335
