### ISSUE TITLE
gbOpen JAM ADM1 and 2 are duplicates

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1664]
**Describe the Error**
gbOpen Jamaica ADM1 and 2 appear to be duplicates of the same admin level.

**Comment by dfornatora** [comment]
ADM1 was uploaded again with small meta correction. The boundaries that were in our ADM3 were actually ADM2, so uploaded as ADM2. ADM3 file should be deleted.
