### ISSUE TITLE
gBOPEN - MMR ADM 1+3 incorrect metadata? 

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1675]
**Describe the Error**
gbOpen for Myanmar ADM1 and 3 appears to have inccorect source, link, and year metadata. Both list OpenStreetmap in the boundarySource-1 and licenseSource fields. However, boundarySourceURL links to http//geonode.themimu.info/layers/?limit=5&offset=10, which is simply a list of several Myanmar related admin datasets, most of which are much more recent than 2014 as listed in the boundaryYear field. So the boundarySource-1 and boundarySourceURL field should be specified to which specific dataset was used and the boundaryYear field updated to reflect that.

**Comment by lydiatroup** [comment]
creating a new issue for the adm1 for tracking purposes so this doesn't get lost with the upload/merging of the adm3!
