### ISSUE TITLE
New CGAZ for 4.0

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1681]
Placeholder issue to remind me to generate the new CGAZ surface for 4.0

**Comment by DanRunfola** [comment]
Closed by https://github.com/wmgeolab/geoBoundaries/commit/fe1635f3ba0cb3eecea15899a7dfbdaf731945b0!

That's a wrap for 4.0!

**Comment by leeberryman** [comment]
Looks like a lot of attribute data in CGAZ shapefiles are missing. in adm0, Country_NA is null. in adm1 shapeName, ADM1_Name, admin1Name, Type, ISO_Code, Country_NA, ISO_CODE_1 are all null. in adm2 same issue. @DanRunfola

**Comment by leeberryman** [comment]
geojson adm0 doesn't include any field but iso_code, is this what is intended @DanRunfola I don't remember v3 cgaz being this way.

**Comment by DanRunfola** [comment]
Please keep flagging in here - CGAZ0 should definitely have more attribute data; it looks like the clearing of the attribute data in CGAZ ADM1/2 broke down somewhere in the build, so I'll have a look at that.

**Comment by DanRunfola** [comment]
Thanks to https://github.com/wmgeolab/geoBoundaryBot/pull/4 , this has now been cleaned up and a new CGAZ has been pushed.
