### ISSUE TITLE
[BOUNDARY ERRATA] Hole in MDA_ADM0

### ISSUE THREAD

**Issue by MichaelR-geoLab** [wmgeolab/geoBoundaries#1688]
**Describe the Error**
A clear and concise description of what the error is - please provide sources as appropriate.

Hole in MDA_ADM0

**Screenshots**
If applicable, add screenshots or images to help explain your problem.

**Additional context**

**Comment by DanRunfola** [comment]
This was closed by https://github.com/wmgeolab/geoBoundaries/pull/1689
