### ISSUE TITLE
CGAZ ADM0 has wrong iso+name for several countries

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1695]
**Describe the Error**

In the CGAZ ADM0 High and Low Res datasets, the fields 'shapeISO' and 'shapeName' are sometimes set to 'None' or sometimes in the wrong field. The affected countries that need fixing are: 

- {'shapeName': 'Kosovo', 'shapeISO': 'None', 'shapeID': 'XKX-ADM0-3_0_0-B1', 'shapeGroup': 'XKX', 'shapeType': 'ADM0'}
- {'shapeName': 'PHL', 'shapeISO': 'None', 'shapeID': 'PHL-ADM0-3_0_0-B1', 'shapeGroup': 'PHL', 'shapeType': 'ADM0'}
- {'shapeName': 'Antarctica', 'shapeISO': 'None', 'shapeID': 'ATA-ADM0-3_0_0-B1', 'shapeGroup': 'ATA', 'shapeType': 'ADM0'}
- {'shapeName': 'None', 'shapeISO': 'None', 'shapeID': 'CHE-ADM0-3_0_0-B1', 'shapeGroup': 'CHE', 'shapeType': 'ADM0'}

https://www.geoboundaries.org/data/geoBoundariesCGAZ-3_0_0/ADM0/simplifyRatio_25/geoBoundariesCGAZ_ADM0.geojson

https://www.geoboundaries.org/data/geoBoundariesCGAZ-3_0_0/ADM0/simplifyRatio_10/geoBoundariesCGAZ_ADM0.geojson

**Comment by DanRunfola** [comment]
I am just about to rebuild CGAZ with new code for the 4.0 release, so this
issue should be resolved.

Other issues will emerge, I am sure :)
