### ISSUE TITLE
URLs in the boundarySource fields? 

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1696]
**Describe the Error**

There's a small handfull of sources that list a URL in 'boundarySource-1' and 'boundarySource-2'. For consistency and since the URL is already listed under 'boundarySourceURL', I think this should instead spell out the name or organization that owns or last edited the data?

**Comment by DanRunfola** [comment]
I have done a full pass on these, and believe this is now corrected.
