### ISSUE TITLE
Meaning and usage of "sourceDataUpdateDate"? 

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1697]
**Describe the Error**

Anyone have any insight to the meaning of the 'sourceDataUpdateDate' field? I couldn't find it in [the guidelines](https://github.com/wmgeolab/geoBoundaries/blob/main/CONTRIBUTING.md). 

For instance, in gbOpen AFG-ADM0/1/2, on the source website below, all date entries incl. "Data published", "Info updated", and "Published Date" are set to "May 6, 2014". Nothing seems to have been done to the dataset in terms of editing, cleaning, or otherwise since 2014, but the 'sourceDataUpdateDate' is set to June/July 2021. In fact, it seems every single gbOpen boundary has a 'sourceDataUpdateDate' in 2020 or 2021. 

https://hub.arcgis.com/datasets/2b63527870ef416bacf83bcaf388685f_0/explore?location=33.932747%2C67.680767%2C6.00

**Comment by DanRunfola** [comment]
Moving this to the master sticky issue.
