### ISSUE TITLE
New estimates for the SALB boundaryYearRepresented

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1699]
**Describe the Error**

For the boundaries that are sourced from SALB, they appear to be given the wrong 'boundaryYearRepresented'. It looks like these have been set based on the date listed above the respective dataset on the SALB country pages, which makes sense. 

However, after some digging into the historical tables for the countries that have them, it appears rather that the dates listed above each dataset is consistently the 'valid from' or the start date of the temporal validity of the dataset. Below are screenshots for Cameroon: 

![image](https://user-images.githubusercontent.com/6413369/129453030-dc7b3bfc-6a2d-4555-922a-50181695b378.png)

![image](https://user-images.githubusercontent.com/6413369/129453062-8c497a10-5813-4001-9ed2-893aed99c181.png)

The historical tables also describe the end date of the dataset's temporal validity, which would be the latest year represented by the boundaries (see above). But the historical tables aren't available for all countries and don't always contain this information. Instead, most of the SALB shapefiles also have a 'DATSOR' field, which [according to this](https://github.com/un-vector-tile-toolkit/salt) means 'Date of source/date of the receipt of the dataset', which corresponds to the temporal validity end date in the historical change tables. Based on the DATSOR field when available or the historical change table, I arrived at the following years for the 'boundaryYearRepresented' fields, which gives more contemporary validity than what's currently listed: 

![image](https://user-images.githubusercontent.com/6413369/129452953-7e3fee9f-830a-4f93-a49c-aff8b3f7f136.png)

**Comment by DanRunfola** [comment]
Thanks for reporting this.  I have been in communication with UN SALB, and they are in the midst of updating ALL of their data to have a "valid to" date, which we will want to use to update our dates.  This will be roughly end-of-Sept; they're going to alert me when we can update.

**Comment by DanRunfola** [comment]
Ok - we have now updated oru data to "valid to" dates where they are available, and will be continuing to update SALB information as they update their own metadata.
