### ISSUE TITLE
[BOUNDARY ERRATA] PHL ADM2 data

### ISSUE THREAD

**Issue by ricsatjr** [wmgeolab/geoBoundaries#1704]
**Error**
PHL ADM2 data: missing province "Davao Occidental"

**Additional context**
Davao Occidental was created in 2013 [https://en.wikipedia.org/wiki/Davao_Occidental](url). 
It is a listed province in Philippine Statistics Authority (cited source by geoBoundaries) as of 2021.  [(https://www.psa.gov.ph/classification/psgc/?q=psgc/citimuni/118600000)](url)

**Comment by DanRunfola** [comment]
Thanks for the report on this - we'll get this updated / pushed ASAP.  It won't quite make it into 4.0, but hopefully very shortly after (a week or two I would guess).
