### ISSUE TITLE
API ConnectionError

### ISSUE THREAD

**Issue by ricsatjr** [wmgeolab/geoBoundaries#1709]
**Describe the Error**
Geoboundaries is down. 

requests.get returns: 
"ConnectionError: HTTPSConnectionPool(host='www.geoboundaries.org', port=443): Max retries exceeded with url: /gbRequest.html?ISO=PHL&ADM=ADM2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f04d3b82370>: Failed to establish a new connection: [Errno 110] Connection timed out'))"

**Additional context**
Error since around Aug 31 7pm (GMT+8) and upto this writing.

**Comment by DanRunfola** [comment]
The gb v1 API has had intermittent downtime for the last 12 hours or so, and is up (but slow) as of this writing.

I recommend moving any scripts over to the new, much more resilient v2 API 
 documented here: https://www.geoboundaries.org/api.html .  It will not be prone to the types of server errors that are plaguing the v1 api today, and also contains the newer gB 4.0 data that just launched.
