### ISSUE TITLE
[BOUNDARY ERRATA] IRL ADM2 and ADM3 are identical

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1711]
Data has been duplicated for IRL between ADM2 and ADM3 just different shapeID generated.

**Comment by sgmurphy216** [comment]
Oof. Absolutely correct, Lee- thanks for pointing this out. Will add this to the list!

**Comment by DanRunfola** [comment]
I'm going to go ahead and pull ADM3 until we get this one resolved.

**Comment by lydiatroup** [comment]
ireland 3 was removed
