### ISSUE TITLE
API returns corrupted unicode for Gāum̐pālikā for NPL ADM3

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1713]
Noting that there are still instances of unicode being corrupted.  I haven't looked if this is corrupted in the source geodata yet or not.

**Comment by DanRunfola** [comment]
Just to confirm - this isn't actually the API, but rather the geojson / shapefile attribute itself, right?

The API doesn't return individual names, so I'm assuming that, but want to make sure there isn't something crazy going on :)

Dan

**Comment by leeberryman** [comment]
It is the canonicalBoundary attribute but it must be my client application that corrupted it.  I did it once more differently and the api is fine.



Lee Berryman
________________________________

**Comment by DanRunfola** [comment]
Ah, got it.  But - good!  I'll close this out then.
