### ISSUE TITLE
gB Authoritative LKA

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#1724]
Need UN SLAB data for LKA (ALL ADM Levels EXCEPT ADM2 and ADM4)

**Comment by lydiatroup** [comment]
need adm 3 for this one as well (if it exists)

**Comment by hadleyday** [comment]
No data on ADM 3, only can upload levels 0-2

**Comment by DanRunfola** [comment]
https://github.com/wmgeolab/geoBoundaries/pull/1808 does ADM1

**Comment by DanRunfola** [comment]
https://github.com/wmgeolab/geoBoundaries/pull/1807 Does ADM0
