### ISSUE TITLE
[BOUNDARY ERRATA] CHL ADM3 Update

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1730]
OCHA updated CHL ADM3 with a more recent dataset than what we have today:
https://data.humdata.org/dataset/chile-administrative-level-0-country-1-region-region

**Comment by DanRunfola** [comment]
Note for whoever picks this up, sources should be:

Source 1: La Biblioteca del Congreso Nacional de Chile (BCN)
Source 2: OCHA ROLAC

**Comment by carolinamonrivera** [comment]
Update: file already clean -- uploading LFS on friday for CHL_ADM3

**Comment by mmyrte** [comment]
Should check for a future version: the commune of Tocopilla is present twice in the current version; however, one of them is actually Pozo Almonte:

- Pozo Almonte -> `CHL-ADM3-31580391B86661872`
- Tocopilla -> `CHL-ADM3-31580391B71776712`

I don't have time to pick this up, but thought I'd at least report it.

**Comment by DanRunfola** [comment]
Thank you for this report @mmyrte - note we're a little slow over the summer, but I hope to get this updated as soon as we can.

**Comment by mmyrte** [comment]
> Note for whoever picks this up, sources should be:
> 
> Source 1: La Biblioteca del Congreso Nacional de Chile (BCN) Source 2: OCHA ROLAC

Happening by the Chilean data again; they're at https://www.bcn.cl/siit/mapas_vectoriales

I really will have to learn you guyses PR procedures, would be great to contribute. Too little time, as ever.

**Comment by 11helenab** [comment]
Closed, Pull Request #3929
