### ISSUE TITLE
Clarification on sourceDataUpdateDate metadata

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1741]
I was previously under the impression that sourceDataUpdateDate in the metadata csvs referred to the last date modification/edits were made by the data publishers to the source data. Then i realized this is not described in the contributor guidelines and none of the meta.txt files contains this information, but rather that the build script automatically generates this based on [the date that the zipfile was committed to the sourceData folder](https://github.com/wmgeolab/geoBoundaryBot/blob/377a325812beedb4fa7d6adb037da02971d63b08/gbBuild.py#L365). 

Not sure how much of a question this is, only perhaps to confirm that this is the intended meaning of the metadata entry? Also to check if maybe adding sourceUpdated as another required meta.txt field when contributing data could be considered in the future? I think this could be a useful aspect to track and esp helpful in terms of knowing whether a dataset is the most recent for continuously updated sources.

**Comment by DanRunfola** [comment]
Moving this to the master sticky issue.
