### ISSUE TITLE
Guidelines for handling water boundaries

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/geoBoundaries#1743]
So the contributions guidelines state that geoBoundaries covers terrestial boundaries only, and should not extend into water. I was wondering when one does encounter a source containing water boundaries, are there any recommended guidelines for contributors / how is this typically handled by the team? Are there any recommended coastline data sources to use for clipping the data to the coastline? 

On another note, I've seen [talk of automating coastline clipping on the backend](https://github.com/wmgeolab/geoBoundaries/issues/27#issuecomment-713731561), which I fully agree would be very useful and could probably be easily implemented as part of the gbBuild.py script. Maybe the meta.txt file could include an optional water boundary flag, which would indicate that the clipping operation should be applied (to avoid modifying a country's self-defined coastal outline)? If and until clipping to remote imagery is implemented, I'm sure there are a few global coastlines vector datasets out there made specifically for these purposes.

**Comment by DanRunfola** [comment]
@karimbahgat I am closing this ticket, as I am working on consolidating some issues to a single master post. Just FYSA.  Should be back up by EOB today.
