### ISSUE TITLE
COD ADM2 & ADM3

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1746]
It appears that ADM2 and ADM3 are describing the same admin boundaries and are duplicates from two different data sources.  There is one more admin boundary in ADM2 polgons (189) primary source HDX than in ADM3 (188) primary source Referential Geographique Commune.

**Comment by dfornatora** [comment]
@leeberryman Thank you for this issue. This was actually discovered over the summer, but the ADM3 file was never deleted. Our current ADM2 is more recently updated.
Link to PR deleting from release data: /pull/1881
and to deleting from source data: /pull/1882

**Comment by DanRunfola** [comment]
Closed by https://github.com/wmgeolab/geoBoundaries/pull/1881
