### ISSUE TITLE
gB Open PAK ADM2

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#1751]
need a new file for PAK ADM2 - no more osm

assigned to amanda

**Comment by leeberryman** [comment]
@lydiatroup I have an adm2 and adm1 that the geometry alligns with the adm3 file for PAK that my team contributed a few months back.  Do you want us to submit those too?

**Comment by leeberryman** [comment]
@sgmurphy216 I see all the issues being created to deprecate ODbL license in 5.0.  Some of the data my team created we released with this license, but if this isn't an acceptable license for GeoBoundaries uses I'd like to change it.  Let me know so we can adjust.  Thanks.

**Comment by sgmurphy216** [comment]
> @sgmurphy216 I see all the issues being created to deprecate ODbL license in 5.0.  Some of the data my team created we released with this license, but if this isn't an acceptable license for GeoBoundaries uses I'd like to change it.  Let me know so we can adjust.  Thanks.

Working up acceptable license list for 5; will share ASAP. Also, any additional PAK contributions would be great! The full list of our boundaries is now available at www.geoBoundaries.org under the 'View Data' tab- any contributions we're missing are more than welcome.

Thanks as always Lee.
