### ISSUE TITLE
gB OPEN SVN ADM1

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#1857]
need a new file for SVN ADM1 (no humdata, share-alike, or odbl)

**Comment by hadleyday** [comment]
https://international.ipums.org/international/gis_harmonized_1st.shtml

**Comment by hadleyday** [comment]
https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts#nuts21
