### ISSUE TITLE
[BOUNDARY ERRATA] Zambia ADM1

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#1991]
Zambia ADM1 sourcing is likely incorrect, as DMMU is not the holder of any formal boundaries.

This appears to be an error from the source we're using (humdata).

However, our ADM2 is accurate.  So we should rebuild ADM1/0 from our own ADM2, and update the sources accordingly!

**Comment by DanRunfola** [comment]
One better - Olena already built the ADM1, so we can just grab this!
https://zambia-nsdi-mlnr.hub.arcgis.com/datasets/6fe71ff483ab491782c8524ec3d1a3b8_0/about

**Comment by justinelliotmeyers** [comment]
Do you have the original source (webpage/ data/ metadata) where these were downloaded from showing those Terms of Use? @DanRunfola ?  Thanks

**Comment by justinelliotmeyers** [comment]
![screencapture-zambia-nsdi-mlnr-hub-arcgis-datasets-6fe71ff483ab491782c8524ec3d1a3b8-0-about-2022-01-07-13_27_24](https://user-images.githubusercontent.com/5324316/148589838-17f7a3dc-9bf6-4c05-a6e4-058c714c3bea.png)
dissolved from district - then a cc-by license. Where can i find the districts page showing the cc-by part?

**Comment by DanRunfola** [comment]
The source for this was the same as the ADM2 we currently have in geoBoundaries, so it would be:

boundaryID : ZMB-ADM2-96606910
boundaryISO : ZMB
boundaryType : ADM2
boundaryYear : 2020
boundarySource-1 : GRID3
boundarySource-2 : Office of the Surveyor General
boundaryCanonical : Districts
boundaryLicense : Creative Commons Attribution 4.0 (CC BY 4.0)
licenseDetail : 
licenseSource : https//data.grid3.org/datasets/GRID3
boundarySourceURL : https//data.grid3.org/datasets/GRID3

**Comment by justinelliotmeyers** [comment]
Thank you!

**Comment by dfornatora** [comment]
This was resolved by PR #2247
