### ISSUE TITLE
[BOUNDARY ERRATA] LATVIA new admin structure

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#1996]
Also as I was looking up values for canonicalBoundaries I found Latvia has new admin structure that is significantly different as of 1 July 2021.  https://en.wikipedia.org/wiki/Administrative_divisions_of_Latvia

**Comment by justinelliotmeyers** [comment]
https://revolutionarygis.wordpress.com/2021/04/20/latvia-2021-administrativas-teritorijas-shapefile/

**Comment by leeberryman** [comment]
@justinelliotmeyers nice!  @DanRunfola this link Justin sent has CC 4.0 license
