### ISSUE TITLE
[BOUNDARY ERRATA] AGO ADM1 has ADM1_NAME instead of shapeName

### ISSUE THREAD

**Issue by chapmanjacobd** [wmgeolab/geoBoundaries#2001]
**Describe the Error**

ADM1
ADM1_NAME | MALANJE

https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/AGO/ADM1/geoBoundaries-AGO-ADM1.topojson

The other ADM levels are OK

**Comment by DanRunfola** [comment]
This was corrected with a new dataset a bit ago, just cleaning up by closing this out.
