### ISSUE TITLE
gb Authoritative ALL layers Metadata update

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2008]
date on **all** UN SALB (authoritative) meta files for **ALL** adm levels need to be updated to the date in

1)download UN Salb data from un salb site, record date present in the attribute table
2)download existing gB files from code -> source data -> gb Authoritative
3)update metadata date to reflect date found in step 1
4)reupload file

this requires going through ALL of the UN salb layers (all gb auth) and updating the dates. this is an URGENT issue to fix

**Comment by SidonieH** [comment]
Costa Rica (CRI) has no date in SALB @lydiatroup

**Comment by SidonieH** [comment]
Haiti (HTI) has no date in SALB @lydiatroup

**Comment by SidonieH** [comment]
- ISL (Iceland) has a earlier date in the attribute table (2016) than the from date on the website (2017)
- ROU (Romania) no date in SALB
- TGO no date in SALB
- ZMB (Zambia) no dat ein SALB
