### ISSUE TITLE
gB Open CAN ADM0-3

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2025]
need a new file for these adms

**Comment by maxmalynowsky** [comment]
Addressed in following:

https://github.com/wmgeolab/geoBoundaries/pull/2395
https://github.com/wmgeolab/geoBoundaries/pull/2396
https://github.com/wmgeolab/geoBoundaries/pull/2397
https://github.com/wmgeolab/geoBoundaries/pull/2398

**Comment by lydiatroup** [comment]
@hadleyday can you knock out the adm3 for this issue so we can close it?
