### ISSUE TITLE
[BOUNDARY ERRATA] gbOpen MYS_ADM3

### ISSUE THREAD

**Issue by MichaelR-geoLab** [wmgeolab/geoBoundaries#2149]
**Describe the Error**
A clear and concise description of what the error is - please provide sources as appropriate.
Potential MYA_ADM3 file has many overlapping boundaries and holes

[MYS3.zip](https://github.com/wmgeolab/geoBoundaries/files/8133782/MYS3.zip)

**Comment by lydiatroup** [comment]
closed by pr #2196
