### ISSUE TITLE
CGAZ AFG ADM 1-2

### ISSUE THREAD

**Issue by aarasmith** [wmgeolab/geoBoundaries#2168]
In the current geoJSON distribution of CGAZ the `shapeName` field is null for AFG admin 1 and admin 2. In the individual AFG country files this data is in columns titled `PROV_34_NA` and `DIST_34_NA` respectively

**Comment by sgmurphy216** [comment]
Thanks for letting us know! We'll look into this and get back to you.

**Comment by DanRunfola** [comment]
This has been fixed as of gB 5.0.

![image](https://user-images.githubusercontent.com/7882645/217346557-34a3f4fa-4e6e-4ae5-9f46-0c1041a63eda.png)

Thank you for the report, and sorry the turn-around is so long right now.

@all-contributors add @aarasmith to ideas
