### ISSUE TITLE
gB Open MMR ADM1

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2219]
Either can correct the meta if the current file has a compatable license, otherwise find a new file and replace it!

gbOpen for Myanmar ADM1 appears to have inccorect source, link, and year metadata. Both list OpenStreetmap in the boundarySource-1 and licenseSource fields. However, boundarySourceURL links to http//geonode.themimu.info/layers/?limit=5&offset=10, which is simply a list of several Myanmar related admin datasets, most of which are much more recent than 2014 as listed in the boundaryYear field.

**Comment by ssheminway** [comment]
Couldn't find a map to georeference without a share alike license
