### ISSUE TITLE
NOR_ADM1 Attribute table update

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2220]
this iso codes in the attribute table all appear as "null." they should be the iso codes as found on this [site](https://www.iso.org/iso-3166-country-codes.html) -> open browsing platform, using the codes listed in the 3166-2 codes column

**use the file found in [this pr](https://github.com/wmgeolab/geoBoundaries/pull/1989) and update the iso codes in the attribute table and reupload to that existing pr** (ask if you need a refresher on how to do that)

**Comment by SidonieH** [comment]
How do I download the data? Do I need to run the code?
