### ISSUE TITLE
Russia ADM2 - column name show as question marks `?????`

### ISSUE THREAD

**Issue by Rub21** [wmgeolab/geoBoundaries#2249]
**Describe the Error**
Russia  admin-2 column name show as incorrect! The name column show in question marks `?????`

Source:  https://github.com/wmgeolab/geoBoundaries/blob/main/sourceData/gbOpen/RUS_ADM3.zip?raw=true

**Screenshots**
![image](https://user-images.githubusercontent.com/1152236/165105691-8644f5f7-4572-40cb-8736-447f446e5bef.png)

**Additional context**
Russia  admin-0 and admin1 show  in a correct way.

![image](https://user-images.githubusercontent.com/1152236/165106337-682f90d2-7e22-40f0-a01b-e39d971a2cb3.png)
![image](https://user-images.githubusercontent.com/1152236/165106384-e3aba53e-fee6-416e-8be9-23049b09f615.png)

cc. @yunica @geohacker

**Comment by lydiatroup** [comment]
Thank you for finding this bug for us! We will try to fix this issue asap!

**Comment by dfornatora** [comment]
After looking into this, there is no available data with the appropriate license we can use. [https://maps.princeton.edu/catalog/stanford-td486fb7677 ](https://maps.princeton.edu/catalog/stanford-td486fb7677) has information at this administrative level with the names, but it is unable to be used in our dataset.

**Comment by DanRunfola** [comment]
@dfornatora Do we have the original data anywhere?  I.e., it looks like our ADM2 had the names, and they got scrapped due to some sort of encoding issue.

**Comment by lydiatroup** [comment]
@dfornatora @DanRunfola https://drive.google.com/file/d/1RhrFw-_6QvLmneAKABuOxy8vI_GFMuQ-/view?usp=sharing
the link above has the original dataset. It is an incompatable license type but I could see the value in uploading it with an outdated license type that still has the names
