### ISSUE TITLE
[BOUNDARY ERRATA] Duplicated shapeID

### ISSUE THREAD

**Issue by slaperche-zenly** [wmgeolab/geoBoundaries#2289]
Are `shapeID` supposed to be unique?

I thought that the `shapeID` field was an ID that could be used to uniquely identify a shape.
But I've found around ~2100 shapeID that are use 2 or 3 times for different shapes.

Most of them are in `IND-ADM5` (2136), but there is also a few in `FRA-ADM5`  (6), `DEU-ADM3` (2), `IRL-ADM2/ADM3` (34), `LKA-ADM4` (1) and `MDG-ADM4` (3).

Examples:
- `DEU-ADM3-59448661B93935703`: used by `Uedem` and `Mittweida`
- `FRA-ADM5-35783486B53035589`:  used by `Saulnières` and `Montmeyran`
- `IRL-ADM3-65391444B83003623`: used by `Clonmowley` and `Crossrah`

**Comment by DanRunfola** [comment]
This has now been resolved by increasing the length of the generated shapeID in 5.0.  If you see any remaining issues please let me know.

@all-contributors add @slaperche-zenly  to ideas
