### ISSUE TITLE
CGAZ shapeISO column empty 

### ISSUE THREAD

**Issue by cclarkson** [wmgeolab/geoBoundaries#2290]
I have been downloading and successfully using the v3 adm1/adm2 GCAZ Shapefile [data](https://www.geoboundaries.org/data/), but when I switch to the v4 (?) [data](https://www.geoboundaries.org/downloadCGAZ.html), there are several empty columns, including the shapeISO. I was wondering why the format has changed and if these columns are meant to be empty?

**Comment by cclarkson** [comment]
Hi @DanRunfola, many thanks, I am looking at admin level 1, this column was populated in v3.

**Comment by DanRunfola** [comment]
Thank you for this - I'll look into it before the next CGAZ build.  Just FYSA we're a bit slow over the summer, but high on the priority list.

**Comment by DanRunfola** [comment]
@cclarkson This was resolved a little while ago, just closing this out now.  

@all-contributors add @cclarkson   to ideas
