### ISSUE TITLE
[BOUNDARY ERRATA] The Gambia Central River admin 1 split is incorrect

### ISSUE THREAD

**Issue by cclarkson** [wmgeolab/geoBoundaries#2291]
In The Gambia, the Central River admin 1 region has, in recent years, been split into two. It looks like this has been done horizontally, with Kuntaur being the new northern admin 1 region and Janjanbureh becoming the southern admin 1 region 
_e.g._ DOI:[10.1371/journal.pone.0139354](http://dx.doi.org/10.1371/journal.pone.0139354) and on The Gambia Bureau of Statistics [website](https://gambia.opendataforafrica.org/).

However, on wikipedia, I see some examples where the this division has instead been made vertically , creating an eastern Kuntaur and and western Janjanbureh, though I can see any "official" recognition of this. The data in geoboundaries follows this (incorrect?) division.

Additionally, the admin 1 shapeISO is identical for both Kuntaur and Janjanbureh, `GM-M`, relating the old Central River region. I would have thought that new shapeISOs would have been created when Central River was split, though I can't find any official new shapeISOs online.

**Comment by DanRunfola** [comment]
Thank you for this submission!  Just as a note we're a bit slow over the summer (being based out of a university!) but we'll try to get this into the database ASAP.

**Comment by kpupkiewicz** [comment]
Good spot, @cclarkson . You’re correct about Kuntaur & Janjanbureh - all official Gambian sources have that boundary division at the river border. I have no idea how that error on Wikipedia came about 🤔 Check out the metadata in the PR above for the updated source information. Hopefully tomorrow afternoon I can add a new GMB_ADM3 from this source as well.
