### ISSUE TITLE
gB Humanitarian ETH ADMIN 1 2 3 

### ISSUE THREAD

**Issue by MichaelBrandonFalk** [wmgeolab/geoBoundaries#2294]
UN OCHA shapefiles on Geoboundaries are out of date. The updated UN OCHA shapefiles are available at [https://ethiopia.africageoportal.com/maps/africageoportal::ethiopia-adminboundaries/about ](https://ethiopia.africageoportal.com/maps/africageoportal::ethiopia-adminboundaries/about )

Below is a screenshot of the DBF tables of ADM1 compared. 
![unnamed](https://user-images.githubusercontent.com/102083222/180889797-5a456ed9-2088-4478-84d4-34d3084770a9.png)

Please let me know if there are any further steps I can take to get the updated OCHA information updated for the rest of the world ( I may need to submit that part under a feature request?) This is my first time posting an issue so I appreciate your patience.

**Comment by DanRunfola** [comment]
This will be resolved very shortly by https://github.com/wmgeolab/geoBoundaries/issues/2295 - thank you fo raising.
