### ISSUE TITLE
gB Open RWA ADM5 Village layer

### ISSUE THREAD

**Issue by MichaelBrandonFalk** [wmgeolab/geoBoundaries#2298]
Under geoBoundaries view data page there is an ADM5 village layer viewable from GADM with around 14815 villages. However, under the geoBoundarie download page such a layer does not exist. I understand there may be some licensing issues with the data source, but it appears to be  stated on the GADM website "You are allowed (but not required) to publish these articles (and the maps they contain) under an open license such as CC-BY " https://gadm.org/license.html 

I'm not sure what the exact requirements would be for geoBoundaries. It was recommended to me to start a discussion on this so we could put our heads together and figure out how to get the village data into the geoBoundaries download section. Hopefully I am starting this conversation in the correct place/manner. If there is a better way/place for me to bring up these kinds of issues, please let me know. Thank you. - Brandon Falk

**Comment by justinelliotmeyers** [comment]
I think GADM should be avoided. Test this dataset on and check the license. Enjoy!
https://datacatalog.worldbank.org/search/dataset/0041453

**Comment by leeberryman** [comment]
Thanks @justinelliotmeyers

**Comment by MichaelBrandonFalk** [comment]
Thanks @justinelliotmeyers These appear to be the the same, but agree that it is usually best to avoid GADM. This one has the licensing info very clear. So that's excellent! Thanks again.
