### ISSUE TITLE
[BOUNDARY ERRATA] Guatemala ADM2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#2327]
**Describe the Error**
GTM ADM2 has some holes - not sure if it's in our build or in the source, but we need to check.

**Screenshots**
![image](https://user-images.githubusercontent.com/7882645/183909589-58ca00a0-52c1-4337-b218-4a43f89ab727.png)

**Comment by lydiatroup** [comment]
the top right hole is also present in the source (https://data.humdata.org/dataset/cod-ab-gtm) and is a lake. some research into this indicates the lake itself may not be split into municipalities

**Comment by MichaelR-geoLab** [comment]
Should I make the holes into separate provinces, split them among existing provinces, or leave it be? Not sure about the procedure here.

**Comment by lydiatroup** [comment]
@MichaelR-geoLab It'll depend on which hole it is. Will require some research to see how they are actually split up ie whether it's split or all in one or its own thing. If you don't see anything promising after some research, I would fill in the holes as their own features with them listed as the lake name.
