### ISSUE TITLE
[FEATURE REQUEST] Clarification on license requirements between gbOpen and gbHumanitarian

### ISSUE THREAD

**Issue by maxmalynowsky** [wmgeolab/geoBoundaries#2452]
**Is your feature request related to a problem you run into when using geoBoundaries? Please describe.**

Most OCHA Common Operational Datasets are licensed under "Creative Commons Attribution 3.0 Intergovernmental Organisations (CC BY 3.0 IGO)". My understanding is that the goal of gbOpen is to include datasets licensed CC-BY. Is there any barrier to adopting the same dataset between these two release streams, especially when the source is a local government?

**Describe the solution you'd like**

If there is no issue with using the same datasource for both streams, I would propose a bulk import of existing CODs to replace data sources coming from OSM wambachers or similar sources.

**Comment by DanRunfola** [comment]
This is a hot topic for discussion!

The core challenge here is that we can't trust the licenses that OCHA has on HDX right now, as the data lineages are often missing or confusing.  Now, this isn't *always* true, and I think there are some HDX licenses we could reasonably use, but we can't blanket accept - and, generally, they need to be held to a pretty high standard of evidence before we accept them.  I.e., simply saying "UN OCHA says it's licensed under CC-BY" doesn't actually mean that is true (..or legal).  You've touched on one of the big frusturations within the UN boundary community right now.

A few examples (taken randomly):

https://data.humdata.org/dataset/cod-ab-cmr
--> In "other" there is some discussion of OSM data.  Was this originated from OSM?  If not, why are the IDs there?  If this was "consolidated", what was it consolidated from?

https://data.humdata.org/dataset/cod-ab-jam
--> Literally from GADM :)

https://data.humdata.org/dataset/cod-ab-fsm
--> Tells us where it was downloaded from, but not where the source allows redistribution under CC-BY.  If you go to the source link from there, it doesn't have any licensure information at all.  

https://data.humdata.org/dataset/cod-ab-mar
--> Straight from GAUL, which was under a non-distribute license

**Comment by maxmalynowsky** [comment]
Definately agree with all your points, there are datasets like the ones from GADM that you linked to that I exclude myself when adding to my own project. 

But to use a counter example, Costa Rica being a good one. Currently this is provided by OSM Wambacher in gbOpen, while the COD uses Costa Rica National Statistics Office (NSO). Since the existing source is not compatible with CC-BY anyways, and includes topology issues like missing polygons for admin units, is there any argument against using a COD coming from a government source?

**Comment by maxmalynowsky** [comment]
Summarizing proposed action: make a list of all current gbOpen sources not currently CC-BY compliant, and flag for replacement by an HDX source so long as there isn't an explicit issue with that source (not OSM, GAUL, or GADM).

**Comment by DanRunfola** [comment]
Tentatively closing this out for now, but if further discusion don't hesitate to reopen.
