### ISSUE TITLE
[BOUNDARY ERRATA] - Nigeria Admin2

### ISSUE THREAD

**Issue by antcmn** [wmgeolab/geoBoundaries#2515]
In the Nigeria Admin 2 level Shapefile and GDB (nga_admbnda_adm2_osgof_20170222), the names and codes of two admin2 features are switched. Where Admin 2 shows Safana it should show Sandamu and vice versa.    

Example of  the error (1) - Safana to Sandamu
![image](https://user-images.githubusercontent.com/17455004/192519518-cf6cabe4-26da-4488-9fbf-995f2f60a645.png)

Example of the error (2) - Sandamu to Safana
![image](https://user-images.githubusercontent.com/17455004/192521250-f57a43b0-56db-433f-8855-f071b30315f6.png)

Best regards,

**Comment by DanRunfola** [comment]
@antcmn thanks for reporting this one - we'll take a look ASAP.

@all-contributors add @antcmn   to ideas
