### ISSUE TITLE
Duplicate ShapeID

### ISSUE THREAD

**Issue by Raygone2** [wmgeolab/geoBoundaries#2548]
@DanRunfola,
We think there is a bug in the ShapeID assignment process.  These IND_ADM5 shapeIDs are duplicates.  Please see the attached csv and the screenshots. @leeberryman  & I want to know if we can regenerate shapeIDs for the India data.

Thanks,
@Raygone2 

[duplicates.csv](https://github.com/wmgeolab/geoBoundaries/files/9778923/duplicates.csv)
![IND-duplicate-ShapeID](https://user-images.githubusercontent.com/40348613/195659788-4728017e-ed86-4e38-9f48-0c1e2d172d56.JPG)
![IND-duplicate-ShapeID-single](https://user-images.githubusercontent.com/40348613/195659800-3ae43e38-4c0b-42c7-b516-7ca65fb4e7b9.JPG)

**Comment by DanRunfola** [comment]
Yes - this is a known issue, and impacting layers that have large numbers of extremely small polygons (see https://github.com/wmgeolab/geoBoundaries/issues/2289).  I would be *very* open to solutions here, and would like to have something implemented before 5.0 to resolve this.

The goal is a deterministic algorithm that generates an ID based on the geometry itself.  The problem is the current implementation appears to generate near-identical values for some cases.

The code that is resulting in the error is on lines 435 to 439 here:
https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbBuild.py#L435

This could be as simple as changing the hash algorithm, but I haven't had a chance to test yet.

**Comment by DanRunfola** [comment]
Just to provide a little more context:
Taking the example above, shapeID is:
IND-ADM5-67370122B10563491

The IND-ADM5 is just the concactenation of the ISO/ADM level.

The 67370122 is a hash generated on the basis of the zip file itself in the source folder - this makes it impossible for two different files to have the same hash (i.e., if the metadata changes). This is generated on line 67 (https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbBuild.py#L67)

The "B" is a string I add to delimit.

The "10563491" is, I believe, the troubled piece of the code.  It is what's generated here:
https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbBuild.py#L435

In that, I hash the actual geometry string to (hypothetically) create a unique identifier.  However, as we're seeing, the way that it's being truncated is not resulting in a unique ID in every case.  So I'm pretty sure fixing the algorithm on line 435 is what will fix this. https://github.com/wmgeolab/geoBoundaryBot/blob/main/gbBuild.py#L435

**Comment by leeberryman** [comment]
@DanRunfola Thanks for the insight. @Raygone2 Let's take a look together next week.

**Comment by Raygone2** [comment]
@DanRunfola 
These are the tests that I did based on your suggestion on [https://github.com/wmgeolab/geoBoundaries/issues/2289 ](url)

1.  Take hash of Geometry - Centroid
2.  Take hash of Geometry - Centroid - ShapeName
3.  Take hash of Centroid - Geometry - Centroid
4.  Take hash of Centroid - Geometry - ShapeName - Geometry.Area

Output: with your truncation scheme ( % 10**8),  there were duplicate value in resulting shapeID.

So, I checked how much the truncation space be increased that there are no duplicates.
Output: with (% 10 ** 12) truncation  to the hash value of  Geometry - Centroid there was no duplicates. 
[Note: All the tests are done in IND-ADM5]

But since you don't want to increase the length of shapeID, i propose two methods.

1.  Either we append a numeric or non-numeric key at the end of duplicate keys. if we have two keys with value '1234', then we can do 
-  1234+0 = 1234, 1234+1 = 1235 and so on (integer addition)
-  or 1234 + 0 = 12340, 1234+1 = 12341 and so on  (string concatenation)
-  or  1234 + a = 1234a, 1234+b = 1234b and so on (this is more suitable, in my opinion)

2. Or, we can iteratively work on duplicate values to make them unique. (this is similar to 1.1 above, my only attempt here is to look back behind in the key-space rather than only go forward.)
`while True:
    print("Checking for Duplicates")
    gdf_no_dup = gdf.drop_duplicates(subset=['shapeID'],keep=False)
    duplicates = gdf[~gdf.shapeID.isin(gdf_no_dup.shapeID)]        
    
    if duplicates.empty:
        break
        
    for shapeID in tqdm(pd.unique(duplicates.shapeID)):
        c = 0
        for i,row in duplicates[duplicates.shapeID == shapeID].iterrows():
            if c>0:
                shapeID = row.shapeID.split('B')
                suffix = int(int(shapeID[-1])/2) + c
                shapeID[-1] = str(suffix)
                duplicates.loc[i,'shapeID'] = "B".join(shapeID)
            c+=1
         
    print("merging data")
    gdf = pd.concat([gdf_no_dup,duplicates]))`

**Comment by DanRunfola** [comment]
I am thinking on this - the rationale for the length of the ID is really only related to total size, and I rather suspect moving from 8 to 12 won't have a huge impact (~2 bytes a char / 8 an ID - call it around 10 million boundaries, so we're only talking ~20 megs for the entire database).

Does anyone on this thread see any good rationale for not extending the length of the field?  I was initially also concerned about ESRI being able to open longer field values, but apparently those are bugs that were squashed literally decades ago (so my students tell me - my ESRI experience is circa ArcInfo days).

**Comment by DanRunfola** [comment]
That's a very good question!  @Raygone2 any thoughts you have would be appreciated on that.

**Comment by Raygone2** [comment]
@DanRunfola , @leeberryman 
We can never be certain that only unique id will be generated for each individual entity. 

Code snipped in the image below is how i did my test. I translated the [India, Paktistan, Nepal and Bangladesh] resulting in more than 1million polygons. And for 10**12 scheme gave 2 entites with same ID (1 duplicate value).
![image](https://user-images.githubusercontent.com/40348613/198565875-dae6a49a-fa84-4c6f-942f-c3cace0181fc.png)

[Note: I added sha512 hash value of (Geometry-Centroid) as a seed in addition to Geometry-Centroid for sha256-hash (which is used to generate ID)]

**Comment by leeberryman** [comment]
@Raygone2 so what you are saying is with your proposed solution with a polygon set on 1 million you got two duplicates, right?  What if we used more 1 or 2 more characters?

**Comment by DanRunfola** [comment]
I think it would be reasonable to assume an upper limit of ~1 million Polygons for a given territory.  Even 1 million seems higher than we are likely to ever encounter.  So we could go with 10**14, just to be *extra* safe, assuming that doesn't result in collisions.

(With the note that hashing is always, in edge cases, going to have a very low likelihood of generating a collision).

**Comment by Raygone2** [comment]
@DanRunfola 
Yes, it is unlikely for collision in hashing, but the possibility that two hash value will be truncated to same value (same remainder for any given denominator) is higher. That's been the case. It was not the same hash value, but two hash value resulted in same remainder.

But going up to 14 character solves the issue.
You can see in the image below that with 13 character there is unique value for 1.9million polygons.
and the little addition to the algorithm.

![image](https://user-images.githubusercontent.com/40348613/198672496-bd8b2458-159d-4536-a223-26dc95c70cc3.png)

**Comment by DanRunfola** [comment]
Just to close the loop on this, I am about to push 5.0 (god willing), which now has a 14-digit hash:
hashVal = int(hashlib.sha256(str(geom["geometry"]).encode(encoding='UTF-8')).hexdigest(), 16) % 10**14

**Comment by leeberryman** [comment]
Thanks @DanRunfola & @Raygone2
