### ISSUE TITLE
gB OPEN SYC ADM1

### ISSUE THREAD

**Issue by kandicst** [wmgeolab/geoBoundaries#2624]
**Describe the Error**
Names of Seychelles Admin1s are incorrect.

**Screenshots**
![image](https://user-images.githubusercontent.com/46457277/203404055-cb8e850e-da0d-42c4-8dff-99aea7cbbf6d.png)
As you can see, some of the names are cut off or have a weird encoding. ([geojson link](https://geojson.io/#id=github:wmgeolab/geoBoundaries/blob/main/releaseData/gbOpen/SYC/ADM1/geoBoundaries-SYC-ADM1_simplified.geojson&map=14.08/-4.74164/55.51529))
Ground truth can be found [here](https://en.wikipedia.org/wiki/Districts_of_Seychelles).

**Additional context**
This is probably due to shapefile having a 10 character limit.

**Comment by DanRunfola** [comment]
@jingjli1 Could you take a look at the geoJSONs that were released in 5.0 and see if this is still an issue?  I rewrote the build scripts, and am hoping some of these encoding issues may have been corrected.

This may still be an issue in the shapefile; I don't think the string fields themselves are limited to 10 char, though (just the title, if I remember the shapefile specification correctly).

**Comment by DanRunfola** [comment]
@all-contributors add @kandicst  to ideas

**Comment by 11helenab** [comment]
Closed, Pull Request #3932
