### ISSUE TITLE
[BOUNDARY ERRATA] DEU ADM1

### ISSUE THREAD

**Issue by SvenVw** [wmgeolab/geoBoundaries#2631]
**Describe the Error**
The boundaries for DEU ADM1 seem to be not very accurate. The offset is for some cases > 2km compared with with ADM2 and other sources. It looks therefore that the scale of the source data used for ADM1 is not detailed enough.

**Screenshots**
Comparison between ADM1 (red), ADM2 (green) and OSM (Location: 10.50601,51.68217):

![image](https://user-images.githubusercontent.com/37927107/204851802-08e162ee-5ff6-4f9e-bca7-c2286e0da8cb.png)

**Additional context**
An improvement can be to use the dataset from the German government: https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/nuts-gebiete-1-250-000-stand-31-12-nuts250-31-12.html. The download link is: https://daten.gdz.bkg.bund.de/produkte/vg/nuts250_1231/aktuell/nuts250_12-31.gk3.shape.zip 
The license looks permissive: https://www.govdata.de/dl-de/by-2-0

**Comment by DanRunfola** [comment]
Thank you!  

That license does look like we could use it - at least very similar to CC-BY.

@lydiatroup @dfornatora could one of you grab this?  I'm working on the gb 5 code revisions now :)

**Comment by lydiatroup** [comment]
We have used this license previously. I will assign someone to this issue to update our Germany ADM1 to use this source. Thank you for the suggestion!

**Comment by DanRunfola** [comment]
@all-contributors add @SvenVw  to ideas
