### ISSUE TITLE
Update Ukrainian boundaries by adding KATOTTG codes

### ISSUE THREAD

**Issue by ap-Codkelden** [wmgeolab/geoBoundaries#2649]
Hi there,

the last time when I used GeoBoundaries data for Ukraine admin level 3 I found that the files (as for SHP) don't contain the KATOTTG codes (this is an administrative division codification of Ukraine). The absence of these codes in the data is the cause of complications for research and analysis works and activities.

However, these codes are present in the official spatial data, published by the Ministry of Communities and Territories Development of Ukraine. GeoJSON files were published on the government decentralization-related resource, but due to Russian Federation aggression were removed and at this time available only via WebArchive: 

* [ADM1](https://web.archive.org/web/20220215083643/https://atu.decentralization.gov.ua/ADMIN_UKR/ADMIN_1.geojson)
* [ADM2](https://web.archive.org/web/20220214172142/https://atu.decentralization.gov.ua/ADMIN_UKR/ADMIN_2.geojson)
* [ADM3](https://web.archive.org/web/20210214192625/https://atu.decentralization.gov.ua/ADMIN_UKR/ADMIN_3.geojson)

Is it possible **to update** currently published Ukrainian boundaries for administrative levels 1-3 with the files provided above?

**Comment by DanRunfola** [comment]
Hi @ap-Codkelden - right now, we don't support unique codes (other than ISO codes) for administrative boundaries.  However, this is part of a bigger conversation, as we're trying to figure out what we can feasibly / sustainably offer to the community.  Any suggestions you can offer would be very welcome - right now we've been discussing constructing geometry-based "most likely" joins for this type of data, but it's a while off before we'll have anything implemented.

**Comment by ap-Codkelden** [comment]
Hi Dan! 
At this moment I can't propose any suggestions. I think that I can add desired KATOTTG unique codes to the dataframe I being used. If `shapeID` column is immutable for every shape, it can be used as a key column with GeoBoundaries data.
Thank you!

**Comment by DanRunfola** [comment]
Yes - so long as the geometry doesn't change, we leave the ID the same!  (The actual geometry is what we use to generate the ID).

Closing this out for now, but with a promise we're trying to get a better solution to join codes in the future.
