### ISSUE TITLE
Api: can't get adm4 for iso=SEN

### ISSUE THREAD

**Issue by abdou4ML** [wmgeolab/geoBoundaries#2658]
Hi,
thank you for your outstanding job. I'm wishing you all the best for this new year.
However, using the API, i can't get the ADM4 level for iso=SEN. How come?
Best,

**Comment by DanRunfola** [comment]
Looks like that's because we don't have that layer in the database :) 

https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen/SEN

Definitely happy to receive any contributions!

**Comment by abdou4ML** [comment]
Ok, thank you for your reply
Best,

**Comment by abdou4ML** [comment]
I think that it'll be good for everyone to have a "Not available" return message if the level doesn't exist in your database.
Actually, i'm trying to build a map with the ADM4 level. It seems that it's available somewhere. I keep on searching ...

**Comment by DanRunfola** [comment]
Good luck, and let me know if you find anything.  We go down to ADM2 globally, but can't go beyond that everywhere today.
