### ISSUE TITLE
[BOUNDARY ERRATA] Nigeria ADM2 and ADM1 don't line up

### ISSUE THREAD

**Issue by nickbearman** [wmgeolab/geoBoundaries#2660]
**Describe the Error**
The Nigeria ADM2, ADM1 and ADM0 boundaries do not nest properly. 

![image](https://user-images.githubusercontent.com/6410645/214029582-5c3650db-7aa2-4017-b8b6-a2722ccc8e95.png)
In the image above, ADM0 lines up fine with AMD2 (thin black line) but neither line up with ADM1 (thick black line). 
I suspect this is because ADM2 is from Humdata.org whereas ADM1 is from GRID3. 
GRID3 do to the LGA boundaries (ADM2) so it might be worth using those instead as a source. 

For example, this is GRID3_Nigeria_-_Local_Government_Area_Boundaries (thin line) and grid3_nga_boundary_vaccstates (thick line):
![image](https://user-images.githubusercontent.com/6410645/214030056-1ca6bd8f-1aaf-488b-8075-24c55d75b517.png)

GRID3_Nigeria_-_Local_Government_Area_Boundaries is from https://data.grid3.org/datasets/grid3-nigeria-local-government-area-boundaries-1/explore?location=9.015113%2C8.685290%2C6.61

grid3_nga_boundary_vaccstates  is from https://data.grid3.org/datasets/grid3-nigeria-state-boundaries/explore?location=9.032544%2C8.685290%2C6.82

Any questions, please let me know. 

Best wishes,
Nick.

**Comment by nickbearman** [comment]
Thanks Dan - much appreciated! 

Good luck with the funding :-)

**Comment by lydiatroup** [comment]
Thank you for the note and new sources for our Nigeria files! These sources are indeed better than what we currently have in the database, and I will be uploading them into the database shortly.
