### ISSUE TITLE
gb Open CHL ADM0

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2676]
need a new file for CHL ADM0

**Comment by justinelliotmeyers** [comment]
chl chile? I can help if so 'eh

**Comment by leeberryman** [comment]
@justinelliotmeyers yes.  Do you have a link to data with clear license?

**Comment by justinelliotmeyers** [comment]
https://www.ine.gob.cl/herramientas/portal-de-mapas/geodatos-abiertos
https://www.ine.gob.cl/terminos-de-uso-y-licencia-de-datos-abiertos


Adios!
