### ISSUE TITLE
[BOUNDARY ERRATA] gB Open AUS ADM1

### ISSUE THREAD

**Issue by alex-translation** [wmgeolab/geoBoundaries#2752]
On [geoBoundariesOpen-meta.csv](https://github.com/wmgeolab/geoBoundaries/blob/main/releaseData/geoBoundariesOpen-meta.csv), the value of `staticDownloadLink` for AUS ADM1 is a duplicate of the link for the ADM0 value (https://github.com/wmgeolab/geoBoundaries/raw/de71fe3/releaseData/gbOpen/AUS/ADM0/geoBoundaries-AUS-ADM0-all.zip). Replacing both instances of "ADM0" in the link with "ADM1" does lead to the expected output. 

Here's a screenshot of the current .csv file.
<img width="729" alt="Screenshot 2023-02-08 at 6 17 13 PM" src="https://user-images.githubusercontent.com/82901988/217501528-169053c6-748b-4ec5-b5ea-2bf29d1b6aed.png">

**Comment by DanRunfola** [comment]
Just took a look at this - it's a metadata error in the source file.  I'm going to try and get a fix pushed to this tomorrow.

**Comment by alex-translation** [comment]
Hi @DanRunfola, thanks for getting back to me. Any progress on this? Anything I can do to help?

**Comment by DanRunfola** [comment]
This has just been accepted in - should get pushed to the database tomorrow morning after the build (Wed at the latest - some security issues on GitHub's side that required them to update a server-side key, and may cause some issues).
