### ISSUE TITLE
[BOUNDARY ERRATA] KAZAKHSTAN (KAZ) new admin structure

### ISSUE THREAD

**Issue by aidoskanapyanov** [wmgeolab/geoBoundaries#2779]
**Describe the Error**
The administrative boundaries of Kazakhstan (KAZ) have been updated on November 29, 2022.
According to the new administrative structure, Kazakhstan is now divided into 20 regions (oblystar).
https://en.wikipedia.org/wiki/ISO_3166-2:KZ

**Screenshots**
**Old.**
![image](https://user-images.githubusercontent.com/65722512/222675325-a9484e7f-bd5a-4c99-bc15-d3f6a35e19ab.png)

**New:**
![image](https://user-images.githubusercontent.com/65722512/222675137-da019f7e-4ce9-4500-81c4-10a2f6187a1d.png)

**Additional context**
Unfortunately, I haven't found any new .geojson/.shp files yet.

**Comment by aidoskanapyanov** [comment]
**Update:**
I found latest shapefiles here: https://data.amerigeoss.org/dataset/kazakhstan-administrative-boundaries-taxonomy/resource/86cce6ba-4b79-4b4e-8961-3e6e04308395

**Screenshots:**
![image](https://user-images.githubusercontent.com/65722512/222678454-b2767bc6-4e61-41c4-83c0-5abdb08b92aa.png)

**Comment by lydiatroup** [comment]
Hi @aidoskanapyanov. Thank you for bringing this change to our attention! Unfortunately, due to our strict license requirements we are unable to use the exact file you provided, however I will create a general issue for updating the Kazakhstan regions.
