### ISSUE TITLE
gB Open PER ADM1

### ISSUE THREAD

**Issue by lydiatroup** [wmgeolab/geoBoundaries#2827]
peru adm1!!! current license is incompatible

**Comment by DanRunfola** [comment]
@lydiatroup this is a very exciting issue!!!

(Also - licensure I guess?)

**Comment by emiliaz9** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Peru_Input_Administrative_Boundaries_%285457154471%29.jpg/640px-Peru_Input_Administrative_Boundaries_%285457154471%29.jpg
- Link to picture
