### ISSUE TITLE
[BOUNDARY ERRATA] Topology issue in CGAZ

### ISSUE THREAD

**Issue by vtricaud** [wmgeolab/geoBoundaries#2901]
Hello! Thank you very much for this really really impressive resource!
I wanted to flag that when running the polygons in python I got the following error. 
_TopologyException: side location conflict at 55.552334096285691 26.814208418100367. This can occur if the input geometry is invalid._
Which appears to relate to the Hormozgan polygon in Iran (IRAN) (lat 26.814208418100367 long 55.552334096285691)
I'm not entirely sure what that means...
<img width="424" alt="image" src="https://github.com/wmgeolab/geoBoundaries/assets/90643182/796d166e-4c98-44a7-8e40-a39dd5f3e549">

**Comment by DanRunfola** [comment]
Very interesting - this shouldn't be happening for _any_ of our layers, except some edge cases for CGAZ.

Which file specifically are you using?

**Comment by DanRunfola** [comment]
Perfect, thank you Victor.

I think we might already have a solution for this specific issue in the works; @rohith4444 can you add this to your list of things to take a peak at?

CGAZ itself is a unique case when it comes to our topology, as every individual *country* is topologically valid, but in our current scripts we didn't do the topological checks on the full layer.  We're working on getting a better system in place for that soon.

**Comment by rohith4444** [comment]
Sure, I will. @DanRunfola

**Comment by vtricaud** [comment]
Thank you very much!

**Comment by DanRunfola** [comment]
@vtricaud  I am doing a round of issue cleanup today, and consolidating this issue with a few others. There will be a new issue popping up by EOB today that covers this topic.

**Comment by vtricaud** [comment]
Thank you very very much @DanRunfola and @rohith4444!
