### ISSUE TITLE
gbOpen no shapeISO for ADM1 CIV data

### ISSUE THREAD

**Issue by ahernank** [wmgeolab/geoBoundaries#2902]
When accessing [v5.0.0](https://github.com/wmgeolab/geoBoundaries/raw/v5.0.0/releaseData/gbOpen/CIV/ADM1/geoBoundaries-CIV-ADM1.geojson) or the [current build](https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/CIV/ADM1/geoBoundaries-CIV-ADM1.geojson), all the `shapeISO` appear as `ADM1` rather than the actual ISO codes. This is different from previous versions (e.g. v3) where these were available. Is this expected?

**Comment by rohith4444** [comment]
Ok, @DanRunfola  I will.
