### ISSUE TITLE
gbOpen no shapeISO for ADM1 GIN data

### ISSUE THREAD

**Issue by ahernank** [wmgeolab/geoBoundaries#2903]
When accessing [v5.0.0](https://github.com/wmgeolab/geoBoundaries/raw/v5.0.0/releaseData/gbOpen/GIN/ADM1/geoBoundaries-GIN-ADM1.geojson) or the [current build](https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/GIN/ADM1/geoBoundaries-GIN-ADM1.geojson), all the `shapeISO` codes are empty. This is different from previous versions (e.g. v3) where these were available.

**Comment by DanRunfola** [comment]
See my comment over on https://github.com/wmgeolab/geoBoundaries/issues/2902 - we'll take a look at this as well.
@rohith4444
