### ISSUE TITLE
[BOUNDARY ERRATA] gB Open - Benin boundaries mix-up in maritime region

### ISSUE THREAD

**Issue by ahernank** [wmgeolab/geoBoundaries#2905]
The [Benin boundary](https://www.geoboundaries.org/geoContrast.html?country=TGO&mainSource=geoBoundaries+%28Open%29&comparisonSource=GADM+v4.0.4&mainLevel=1&comparisonLevel=1) seems to be a bit off which makes it include the sea, and not include the strip of land just beneath Togo. If we compare this with the gB Open boundary for [Togo](https://www.geoboundaries.org/geoContrast.html?country=TGO&mainSource=geoBoundaries+%28Open%29&comparisonSource=GADM+v4.0.4&mainLevel=1&comparisonLevel=1), we can see this strip is not included as part of Togo either. 

![Screenshot 2023-05-30 at 16 18 14](https://github.com/wmgeolab/geoBoundaries/assets/17258490/7d88ee79-b547-4366-93b6-f4626453ff22)

![Screenshot 2023-05-30 at 16 24 43](https://github.com/wmgeolab/geoBoundaries/assets/17258490/23d4bac5-d1ce-4783-a800-091b3d146ef1)

**Comment by DanRunfola** [comment]
Hey @ahernank - thank you for flagging this!  We're actually (slowly) working on a global shoreline standardization approach which would resolve this (and many, many) related issues.  I'm going to consolidate this post with a few others and create a new top-level issue to track some of these longer term strategic goals.

Seperately, I'm going to close this for now just for organization purposes, but will be creating the stickied issue that will include this by EOB today!
