### ISSUE TITLE
[BOUNDARY ERRATA] AUS-ADM1 data is missing from the `gbOpen/AUS/ALL` endpoint

### ISSUE THREAD

**Issue by akif503** [wmgeolab/geoBoundaries#2911]
**Describe the Error**
Here [gbOpen/AUS/ALL](https://www.geoboundaries.org/api/current/gbOpen/AUS/ALL/) the second entry should have the link to ADM1 data files, but ADM0 is repeated. 

**Screenshots**
![image](https://github.com/wmgeolab/geoBoundaries/assets/38287808/67112fc5-73a1-4fbf-aac9-fba4a6ade5e1)

**Comment by DanRunfola** [comment]
This should be fixed by the end of the week (6/24 or so) - see PR https://github.com/wmgeolab/geoBoundaries/pull/2802 .

The delay is because our build scripts have been offline for a few weeks because of an issue we ran into with complex geometries in our CAN ADM1 layer :).
