### ISSUE TITLE
[BOUNDARY ERRATA]SPM ADM0

### ISSUE THREAD

**Issue by alex-imb** [wmgeolab/geoBoundaries#2961]
SPM is not covered in current data as an ADM0 boundary.

**Comment by leeberryman** [comment]
@DanRunfola @alex-imb has alot of changes staged to merge and submit.  Can you please add him to wmgeolab so he doesn't have to fork things?  We haven't been able to trigger the bot with the recent commit.

**Comment by DanRunfola** [comment]
Ah, I read these out of order.  Yes, I'll do that now.
