### ISSUE TITLE
[BOUNDARY ERRATA] Gaps between polygons

### ISSUE THREAD

**Issue by Portur** [wmgeolab/geoBoundaries#3196]
**Describe the Error**
I've noticed gaps between polygons of the same ADMx admin levels. I retrieved these polygons using the download key `gjDownloadURL` from `https://www.geoboundaries.org/api/current/<set>/<code>/<ADMx>/` for the non-simplified geojson results.

The expectation is to retrieve the most accurate, non-simplified, boundaries to be used for Point-in-Polygon queries.

Should I be using a different dataset or url?

**Screenshots**
![image](https://github.com/wmgeolab/geoBoundaries/assets/24350810/d60cd291-8582-4e7d-8344-74603845c6c3)

![image](https://github.com/wmgeolab/geoBoundaries/assets/24350810/5b7f8dbe-a0e5-45f4-99e2-06e7dccf7bac)

**Additional context**
Have a great day 🌞

**Comment by DanRunfola** [comment]
Hey @Portur -

We don't guarantee contiguity in our country-specific products, as our goal is to "represent countries as they would represent themselves".  That means there are gaps, overlaps, and other issues between different country borders.  More generally, in this case, it looks like our underlyin source for Andorra is likely a more simplified source than what we have for France, which is an issue we would eventually want to correct.

Basically: country offices don't necessarilly coordinate with eachother!

That said, in CGAZ we _do_ gap fill, as well as identify disputed regions.  We just don't have an equivalent product at the country scale, as it's important that we can always state we're trying to represent countries as they would represent themselves, given that is our formal definition of our goals.  Also helps politically during periods of unrest, as we can represent multiple entities as laying claim to the same piece of land (in the country specific cases), or simply mark an area as disputed in CGAZ.

**Comment by DanRunfola** [comment]
(Closing this as it isn't anything immediatelly actionable, but happy to continue the conversation here).

**Comment by Portur** [comment]
Thanks @DanRunfola
