### ISSUE TITLE
Metadata missing in latest update

### ISSUE THREAD

**Issue by JackDunnNZ** [wmgeolab/geoBoundaries#3370]
The "gB Core Data Update 2023-12-11 18:07" update seems to have removed the shape metadata from the geojson files. For example, if I diff (after formatting) [a file from the latest release](https://github.com/wmgeolab/geoBoundaries/blob/55f27702ac698d96ed27d275afb918e496547fa6/releaseData/gbAuthoritative/SEN/ADM0/geoBoundaries-SEN-ADM0.geojson) against the [previous version](https://github.com/wmgeolab/geoBoundaries/blob/c0ed7b8dc62dabe97cf355622f557ccfe8546f2b/releaseData/gbAuthoritative/SEN/ADM0/geoBoundaries-SEN-ADM0.geojson) it has the following changes:

```diff
         {
             "type": "Feature",
             "properties":
-            {},
+            {
+                "shapeName": "Senegal",
+                "shapeISO": "SEN",
+                "shapeID": "90481962B44486953112186",
+                "shapeGroup": "SEN",
+                "shapeType": "ADM0"
+            },
             "geometry":
             {
                 "type": "MultiPolygon",
```

I am not sure if this removal was intentional

**Comment by DanRunfola** [comment]
No, this was definitely not intentional, and likely related to a multipolygon casting issue we're working on to support rGeoBoundaries.

I'm going to revert the change that likely cause this now; we should have a fix live in a few hours.

**Comment by JackDunnNZ** [comment]
Thanks so much for the quick response, really appreciate it!

**Comment by DanRunfola** [comment]
This has been reverted/fixed.

Fyi, we're in the midst of a much broader code refactor that should prevent issues like this in the future. Apologies for any inconvenience!

**Comment by JackDunnNZ** [comment]
Thank you so much, and thanks for the great resource!
