### ISSUE TITLE
[API] Base API not reflecting current data and/or missing fields

### ISSUE THREAD

**Issue by sgoodm** [wmgeolab/geoBoundaries#3408]
1 - not all items on https://www.geoboundaries.org/api/ contain all relevant fields (e.g., openAvailable may be missing when there is an open dataset for the item)

2 - missing items (e.g., BIH ADM3 is not listed on https://www.geoboundaries.org/api/ but does exist https://www.geoboundaries.org/api/current/gbOpen/BIH/ALL/)

**Comment by DanRunfola** [comment]
Hey @sgoodm - right now that API endpoint is largely undocumented, and I actually  hope to deprecate it at some point in the future.  I think it may have stale data, but not sure without looking back at the code.

For your use case, is there any reason not to use https://www.geoboundaries.org/api/current/gbOpen/ALL/ALL/ ?  I think it will give nearly equivalent information to you, and shouldn't go stale (as I build that at the same time as all the other files).

**Comment by sgoodm** [comment]
Oh that should be perfect. I didn't even see that ALL/ALL was there - got too mixed in with the all the ISO 3 chars.
