### ISSUE TITLE
Potential issue with some GeoJSON file formats

### ISSUE THREAD

**Issue by sgoodm** [wmgeolab/geoBoundaries#3409]
This is a bit of an odd one which I haven't had the chance to fully trace yet. There are a handful of GeoJSONs which when you attempt to read directly from the URL trigger an error. However, when you first retrieve the raw content from the same URL and then read, they work fine.  See below for MRE.

List of boundaries with issue:
CAN-ADM1, AUS-ADM0, PHL-ADM1, PHL-ADM2, NZL-ADM0, NOR-ADM0

```
import requests
import geopandas as gpd

url = "https://github.com/wmgeolab/geoBoundaries/raw/ff0d953b5aa2/releaseData/gbOpen/AUS/ADM0/geoBoundaries-AUS-ADM0.geojson"

# fails with "fiona.errors.DriverError: Failed to read GeoJSON data"
gdf = gpd.read_file(url)

# succeeds
raw_json = requests.get(url).json()
gdf = gpd.GeoDataFrame.from_features(raw_json["features"])
```

Note: 
I've been primarily working off of data from commit ff0d953b5aa2, but have confirmed this was still an issue for a few of the above using the latest commit.

There is a chance this is a client side issue or package issue (e.g., a fault in how GeoPandas / Fiona retrieve files) but upon a brief inspection of the offending files, they all seem to have issues with syntax highlighters. Might just be coincidence given they tend to be larger files, but may reflect some formatting difference.

**Comment by DanRunfola** [comment]
@sgoodm Could you provide a environment YAML or the version you're using for geopandas to help us replicate?

**Comment by sgoodm** [comment]
geopandas 0.14.0
fiona 1.9.5

**Comment by DanRunfola** [comment]
Just as a note: we were able to replicate, but as far as we can tell there isn't any syntax difference between these files and all of the other files in the database.  Following that, after a little digging, my _guess_ is this has something to do with the special URL handling logic geopandas uses:
https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html

Specifically, my guess is that it is trying to chunk the larger files as per:
"When specifying a URL, geopandas will check if the server supports reading partial data and in that case pass the URL as is to the underlying engine, which will then use the network file system handler of GDAL to read from the URL. "

Going to close this one for now, as not apparently something we can correct.  If someone else hits this issue in the future and needs this functionality, it looks like geopandas supports a range of GDAL-ways to more specifically specify how to handle URL retrieval, documented here: https://gdal.org/user/virtual_file_systems.html#vsicurl-http-https-ftp-files-random-access .

For most users, though, probably relying on requests as per your second example is going to be the "easy" way forward.
