### ISSUE TITLE
[BOUNDARY ERRATA] Outdated Namibian ADM2 boundaries

### ISSUE THREAD

**Issue by noahdasanaike** [wmgeolab/geoBoundaries#3484]
**Describe the Error**

The Namibian constituencies (ADM2) were re-drawn in 2013, resulting in ~121 total constituencies from the original 107 that geoBoundaries currently has.

**Comment by DanRunfola** [comment]
Confirming receipt of this one; we'll try to get it knocked out in the ~spring.
