### ISSUE TITLE
IND ADM0 coverage [BOUNDARY ERRATA]

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#3544]
**Describe the Error**
A clear and concise description of what the error is - please provide sources as appropriate.

0586617dca3f0070777669cbb4cd4bb77d4bd367 Git SHA introduced a version of IND's country boundary with very generalized vertices. 
![Mumbai](https://github.com/wmgeolab/geoBoundaries/assets/23552439/92414454-1d17-48a1-b71a-47c92c92655f)
Here is an example that demonstrates how little of Mumbai's landmass intersects with the current ADM0 shapes  

**Screenshots**
If applicable, add screenshots or images to help explain your problem.

**Additional context**

**Comment by DanRunfola** [comment]
We'll get this fixed ASAP, probably just generalize one of our finer granularity layers from your shop.  Hopefully this week.

**Comment by leeberryman** [comment]
Thanks @DanRunfola!

**Comment by alex-imb** [comment]
I don't know if the team has fixed this issue, but I found a simple fix that makes areas like those in the screenshot above look much cleaner. 

1. Get IND ADM0 and IND ADM1, both from gbOpen.
2. Dissolve ADM1 data.
3. Remove false positives (water near the coastline) by getting the intersection between ADM0 and the dissolve of ADM1.
4. Add in false negatives (roads near the coastline) by getting the union between this intersection and ADM0.

If this issue still persists, I'd like to make a PR using this output.

Input
<img width="1465" alt="Screenshot 2024-02-20 at 2 57 38 PM" src="https://github.com/wmgeolab/geoBoundaries/assets/144378377/80ccff34-6291-432f-a39d-968fb1158789">

Output
<img width="1462" alt="Screenshot 2024-02-20 at 2 59 44 PM" src="https://github.com/wmgeolab/geoBoundaries/assets/144378377/87da8876-506a-4ebc-9ca9-e484a3e195aa">


Code
```
import geopandas as gpd
from shapely.validation import make_valid
import shapely

print(f'gpd:\t {gpd.__version__}')
print(f'shapely: {shapely.__version__}')

SHP_EXT = 'shp'
GEO_COL = 'geometry'
CRS = 4326
ISO = 'IND'

def get_input_gdf(
        layer: int,
) -> gpd.GeoDataFrame:
    '''
    Read in current gbOpen data.
    '''
    shp_file = f'/path/to/file/geoBoundaries-IND-ADM{layer}.{SHP_EXT}'
    gdf = gpd.read_file(shp_file)
    gdf.crs = CRS
    gdf.loc[:, GEO_COL] = gdf.geometry.apply(make_valid)
    return gdf

def remove_false_positives(
        adm0_gdf: gpd.GeoDataFrame,
        adm1_gdf: gpd.GeoDataFrame
) -> gpd.GeoDataFrame:
    '''
    Remove geometry from adm0 not present in adm1.
    '''
    adm0_gdf = adm0_gdf.explode(index_parts=False)
    intersection_gdf = adm0_gdf.overlay(right=adm1_gdf, how='intersection')
    intersection_gdf.loc[:, GEO_COL] = intersection_gdf.geometry.apply(make_valid)
    return intersection_gdf

def add_false_negatives(
        intersection_gdf: gpd.GeoDataFrame,
        adm1_gdf: gpd.GeoDataFrame
) -> gpd.GeoDataFrame:
    '''
    Add geometry from adm1 not present in adm0.
    '''
    union_gdf = intersection_gdf.overlay(right=adm1_gdf, how='union', keep_geom_type=True)
    union_gdf.loc[:, 'geometry'] = union_gdf.geometry.apply(make_valid)
    union_gdf = union_gdf.dissolve(as_index=False)
    union_gdf.loc[:, 'geometry'] = union_gdf.geometry.apply(make_valid)
    return union_gdf

def main() -> gpd.GeoDataFrame:
    '''
    Use IND ADM1 from gbOpen to remove false positives (over water) and false negatives (over land) from IND ADM0 from gbOpen.
    Unlike the examples above, do not use a subset of IND ADM1. Use the entire layer instead.
    '''
    ADM0_GDF, ADM1_GDF = get_input_gdf(layer=0), get_input_gdf(layer=1)
    FULL_INTERSECTION_GDF = remove_false_positives(gdf0=ADM0_GDF, gdf1=ADM1_GDF)
    EXPORT_GDF = add_false_negatives(intersection_gdf=FULL_INTERSECTION_GDF, adm1_gdf=ADM1_GDF)
    return EXPORT_GDF
```

**Comment by DanRunfola** [comment]
Hi all -

We should have this fixed in the next build (See PR https://github.com/wmgeolab/geoBoundaries/pull/3556).  

I'm leaving this ticket open for now until we confirm.

With some luck the build will run this evening; our HPC cluster is very busy this time of year so it may be 48 hours before we get our slot.

**Comment by alex-imb** [comment]
The new data looks much cleaner. Thank you the quick turn around!
