### ISSUE TITLE
[BOUNDARY ERRATA] SLE 4 lacking appropriate fields

### ISSUE THREAD

**Issue by alex-imb** [wmgeolab/geoBoundaries#3547]
**Describe the Error**
SLE ADM4 on gbOpen has a different schema from other layers. It either lacks or renames several fields.

- Renamed: "shapeName" renamed to "ADM4_NAME", "shapeType" renamed to "Level"
- Missing: "shapeID", "shapeGroup"

**Screenshots**
Here's what these look in a Jupyter Notebook.

<img width="1064" alt="Screenshot 2024-02-07 at 8 53 09 AM" src="https://github.com/wmgeolab/geoBoundaries/assets/144378377/ca4d809f-a14a-4c0c-b8b9-3091c1ce5fed">

**Additional context**
The missing shapeID column seems like the most concerning part for me. Renaming ADM4_NAME and Level after downloading the data is simple, but recreating the shapeID is not. Is this process documented? If so, I would gladly help fix it.

**Comment by DanRunfola** [comment]
Not quite sure yet - it's probably an issue in our build itself, but we haven't quite isolated what's going on.  @rohith4444 was looking into this yesterday, hopefully we'll know today.

**Comment by DanRunfola** [comment]
This looks like it was a minor error in the data (which we're going to fix right now), and a seperate error in our build (that we're going to fix in the next refactoring).  

Once we fit the data error it should fix the immediate issue; we'll revisit to make sure this can't happen again soon.

**Comment by alex-imb** [comment]
Thanks for digging into this!
