### ISSUE TITLE
gB Open NPL ADM2

### ISSUE THREAD

**Issue by jingjli1** [wmgeolab/geoBoundaries#3634]
ADM2 uses non-standard field for name (DISTRICT). For ADM1, are "Province 1" and "Province 2" actual names or placeholders?

**Comment by SamChristophersen** [comment]
It appears as though ADM2 does use standard field name for (DISTRICT) and as such, the file has been adjusted and resubmitted. The metadata issue in ADM1 was also corrected and submitted.
