### ISSUE TITLE
[BOUNDARY ERRATA] Canadian ADM1 boundaries are too large

### ISSUE THREAD

**Issue by noahdasanaike** [wmgeolab/geoBoundaries#3646]
**Describe the Error**
I'm not entirely sure what's going on here, because the files are too large for me to load into memory, but the Canadian ADM1 boundaries are 500mb whereas the ADM0 and ADM2 files are both around 20mb. I may be wrong but do suspect there's something!

**Comment by DanRunfola** [comment]
Hi @noahdasanaike - in the releases for geoBoundaries, we provide both simplified and unsimplified versions of every file.  Looking at Canada ADM1's zip file, the simplified version is only ~10-20 megs or so.  So, if you're dealing with a system that has limited ram, I'd definitely recommend using that (noting that there are, of course, some tradeoffs with accuracy).

- Dan

**Comment by noahdasanaike** [comment]
@DanRunfola Thanks! Totally missed the different release types in the function call.

**Comment by noahdasanaike** [comment]
You're right, failed to notice the simplified-normal versions. Thanks!
