### ISSUE TITLE
Typo in USA-ADM1

### ISSUE THREAD

**Issue by grim7reaper** [wmgeolab/geoBoundaries#3681]
I was doing some data processing and found a typo (my code to convert the `shapeISO` into a valid ISO 3661-2 code returned an error).

The `shapeISO` value for `South Dakota` is `SU-SD`.
It should be `US-SD`
<img width="934" alt="Screenshot 2024-03-27 at 10 18 57" src="https://github.com/wmgeolab/geoBoundaries/assets/6479907/acff359a-e416-4e19-bd0d-779c029431ba">

Thanks for your work on this project 🙏

**Comment by Sarangaban** [comment]
Closed with #4158
