### ISSUE TITLE
[BOUNDARY ERRATA] Global Layer ADM2 - TCD

### ISSUE THREAD

**Issue by gc-sommer** [wmgeolab/geoBoundaries#4132]
**Describe the Error**
Northern region of CHAD "Tibesti Ouest" does not seem to be correct - looks like some sliver polygons here.

**Screenshots**
![image](https://github.com/user-attachments/assets/ab76f720-d2d0-4c08-a0c3-a100c1ac4dbd)

**Additional context**
Google Maps screenshot of this region
![image](https://github.com/user-attachments/assets/e6c08e1b-a6ba-47e5-88ff-974784139b6c)

**Comment by 11helenab** [comment]
Closed, Pull Request #4178
