### ISSUE TITLE
[BOUNDARY ERRATA] IRL ADM levels do not reflect actual administrative divisions

### ISSUE THREAD

**Issue by Klime65536** [wmgeolab/geoBoundaries#4134]
**Describe the Error**
The current Ireland boundary sets represent Ireland's Provinces (which currently have no administrative function), and Ireland's Local Electoral Areas (LEAs) which aren't administrative in the traditional sense. 

The [Provinces](https://data.gov.ie/dataset/provinces-national-statutory-boundaries-2019) could be retained as ADM1 as they are used quite frequently even if not exactly administratively, but Ireland's primary administrative divisions are the [Local Authorities](https://data.gov.ie/dataset/local-authorities-national-statutory-boundaries-ungeneralised-2024) which are often called "Counties", though they are slightly different to the actual historical counties, below them are the [Municipal Districts](https://data.gov.ie/dataset/municipal-districts-national-statutory-boundaries-ungeneralised-2024). 
After that the [LEAs](https://data.gov.ie/dataset/local-electoral-areas-national-statutory-boundaries-ungeneralised-2024) could be placed if desired, followed by the [Electoral Divisions](https://data.gov.ie/dataset/electoral-divisions-national-statutory-boundaries-ungeneralised-2024), then potentially (of similar merit to the Provinces) by the [Townlands](https://data.gov.ie/dataset/townlands-national-statutory-boundaries-ungeneralised-2024).

**Screenshots**
![image](https://github.com/user-attachments/assets/2d3ace03-3f03-4650-9d3e-7a1f0397b3db)

**Additional context**
This appears to have initially been an error where the local authorities were accidentally replaced with a duplicate of the LEAs, however when the error was noticed in e.g. #1711 the actual error appears to have gone unnoticed and the "duplicate" was instead removed.

**Comment by ejott** [comment]
I updated ADM2 (#4165) using Administrative Areas (used this rather than Counties based on Tailte Eireann stating "the country is divided into 31 administrative counties/cities"), ADM3 (#4166) using the Municipal Districts, and ADM4 (#4167) using the Local Electoral Areas files you pointed us to. I did not add ADM5 because the Electoral Divisions are named with numbers, and we do not typically accept that for our files. Thank you for your help!
