### ISSUE TITLE
Update Mali boundaries

### ISSUE THREAD

**Issue by dickoa** [wmgeolab/geoBoundaries#42]
Hi,

Thanks for this great project. I wanted to know if it's possible to update the source for Mali.

I see that this dataset is currently used (` boundarySourceURL`):
https://data.humdata.org/dataset/mali-admin-boundaries-level-1-2-and-3-including-2017-population-desagregated-by-sexe

but the official common operational dataset (COD) for Mali cleaned by ITOS and validated is this one:
https://data.humdata.org/dataset/administrative-boundaries-cod-mli

I didn't check the difference in terms of topology/geometry but in HDX data with the COD tags are usually the most accurate and the one the humanitarian use. 

Thanks
Ahmadou

**Comment by slfuhrig** [comment]
Hello Ahmadou, 

Thank you for bringing this to our attention. We will examine this issue further to determine if we need to update our boundaries for Mali in our next release. We greatly appreciate your contribution as we strive to have data of the highest possible accuracy. 

Best,
geoBoundaries

**Comment by DanRunfola** [comment]
Open until we've researched :)

**Comment by slfuhrig** [comment]
Let's see what releases (if any) the new data is compatible with and update accordingly.
