### ISSUE TITLE
geoBoundaries OPEN - SALB Licensure Issue - Gabon

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#50]
Gabon (from SALB) has a license issue we will need to either correct or fall back to an alternative source:

- SALB released a validated version of the 2nd level admin level for the January 2000-January 2006 period during its first phase of activity (2001-2011). This is the layer is the one accessible from the HDX
- The layer integrated into GeoBoundaries has itself been adjusted to correspond to the situation observed in the country since February 2013 

Because the original dataset was modified, and we release standardized international boundaries, we will likely need to fallback to an alternative use.  In this case, we also may consider an upstream contribution to SALB if we can get permission.

**Comment by lydiatroup** [comment]
https://data.humdata.org/dataset/gabon-administrative-boundaries 

was updated 2 months ago? may be fixed? look into

if not working: this map can be digitized: https://en.wikipedia.org/wiki/Departments_of_Gabon#/media/File:GabonDepartments.svg
