### ISSUE TITLE
geoBoundaries OPEN - AFG - ADM0,1,2 - Humanitarian License in Open License Set

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#52]
We want to move away from using Humanitarian licenses in our open set; AFG ADM0 eventually needs to be moved to Humanitarian release only.

AFG ADM 0, 1 and 2 have been moved to the authoritative and humanitarian sets; we need to identify an open AFG for gbOpen.

**Comment by memulder** [comment]
Emails requesting data sent to [NSIA](https://nsia.gov.af/services) and [Afghanistan Data Center](http://anhdc.andma.gov.af/)
