### ISSUE TITLE
gb OPEN - CHE ADM 2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#58]
CHE ADM 2 and 3 are currently non-commercial.  As a part of our move towards a more unified product, we need to find alternatives.

The existing CHE ADM 2 and 3 have been moved into our forthcoming Humanitarian release, which allows for more restrictive licensing.

**Comment by DanRunfola** [comment]
https://github.com/wmgeolab/geoBoundaries/issues/58 covers ADM3, but keeping this open while we work on ADM2.

**Comment by sgmurphy216** [comment]
Found a WMS source for ADM2 and ADM3, appears to be properly licensed, super high resolution. Going to continue the data search, if no suitable replacements are found, will digitize.

**Comment by dorianvmiller** [comment]
I recently found and pushed an ADM2 for CHE (#1405) - it looks like that resolves this issue, let me know if I missed anything!

**Comment by dorianvmiller** [comment]
Resolved by #1405
