### ISSUE TITLE
gb OPEN - URY ADM 2

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/geoBoundaries#59]
URY ADM 2 is currently non-commercial. As a part of our move towards a more unified product, we need to find an alternative.

The existing URY ADM2 has been moved into our forthcoming Humanitarian release, which allows for more restrictive licensing.

**Comment by SidonieH** [comment]
It looks like we already have this as open? From OSM?

**Comment by dorianvmiller** [comment]
Resolved by #1583
