### ISSUE TITLE
gB Authoritative - ESP ADM 0-4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#692]
We have at least two gB Open ADMs for ESP that are from their national website, making these files candidates for release under gB Authoritative as well.

**Comment by hadleyday** [comment]
For future reference- this is a website maintained by the Spanish govt containing shapefiles and other geographic data: http://centrodedescargas.cnig.es/CentroDescargas/index.jsp#

**Comment by slfuhrig** [comment]
I'm going to unassign this issue for now so that we can work on gB Open things first.

**Comment by MichaelR-geoLab** [comment]
I should note that no ADM4 level exists for Spain.
