### ISSUE TITLE
Kenya ADM-1 SSCGS shape names

### ISSUE THREAD

**Issue by anelda** [wmgeolab/geoBoundaries#71]
Hi,

Thanks very much for creating a great resource!

I'm accessing your data via the rgeoboundaries R package by a colleague of mine (https://gitlab.com/dickoa/rgeoboundaries).

I'm combining the data with other open data sets and have a question about the shapeName for the following counties in your dataset:

- Elegeyo-Marakwet -  https://elgeyomarakwet.go.ke/ - it appears as if there is a typo and the hyphen is non-standard
- Murang`a - https://muranga.go.ke/ - includes a back tick rather than apostrophe which may cause problems in programming and pattern matching
- Tharaka-Nithi - https://tharakanithi.go.ke/ - the hyphen seems to be non-standard

I know from first hand experience that standardisation of place names is not a simple challenge, but wanted to bring this to your attention in case it is possible (and sensible in your opinion) to change these names.

I'm not sure what additional information you need, but please let me know if I should pinpoint the exact data set.

Thanks again!

Kind regards,
Anelda

**Comment by DanRunfola** [comment]
Hi Anelda,

Apologies, I didn't realize I hadn't responded to this.  We have this in the queue - it should get pushed in either our 3.1 product (our target) or 4.0 worst case.

There are some deeper issues this raises regarding how we handle encoding, on the technical side, so this may end up taking a little longer than it seems like it should.

Thank you for the report!

-Dan

**Comment by anelda** [comment]
Hi Dan!

This is great thanks! All the best with your work. We'll keep using it as part of the afrimapr work (http://afrimapr.org) and will provide feedback here.

Kind regards,

Anelda

**Comment by DanRunfola** [comment]
Accepting a PR that will close this in 4.0!
