### ISSUE TITLE
gbOPEN - BGD - ADM3

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#73]
BGD ADM3 was moved to the humanitarian release. Need to find an alternative for the gbOPEN product.

**Comment by DanRunfola** [comment]
Was duplicated in #933 .  Closing that one and leaving this one open. Bot may get aggresive and try to recreate, copying this here to try and preclude:

====robotid-d7329e7104s40t927830R028o9327y372h87u910m197a9472n2837s649====

**Comment by taraamcl** [comment]
these are "upzilas" but it has been a difficult boundary to find. There are around ~500 of these depending on what source you look at.
