### ISSUE TITLE
gbOPEN - DJI - ADM2

### ISSUE THREAD

**Issue by nmspage** [wmgeolab/geoBoundaries#81]
DJI ADM2 was moved to humanitarian release. Need to find an alternative source for gbOPEN product.

**Comment by memulder** [comment]
You should be able to download the 15 districts (and 6 arrondissements) of Djibouti from [OSM](https://osm-boundaries.com/) but for some reason one of the settings on my computer is not allowing me open up a geoJSON in anything other than the notes app so I cant actually access the boundaries, but I think someone else definitely could.

**Comment by slfuhrig** [comment]
Duplicate
