### ISSUE TITLE
gB Humanitarian - NZL ADM4

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#825]
Fire & Emergency New Zealand recently released a Localities dataset which may serve as ADM4 for NZL.
https://data.linz.govt.nz/layer/104830-fire-and-emergency-nz-localities/

We need to double check to make sure the data is compatible then upload it if so.

**Comment by DanRunfola** [comment]
Closing stale issues for ADM3 and below.

**Comment by missinglink** [comment]
@DanRunfola I have to say it's discouraging to see my contributions closed though an automated process.

**Comment by DanRunfola** [comment]
Hi Peter,

This is reopened over at #824, sorry about the confusion. Thank you for
catching this.

Dan
