### ISSUE TITLE
gB OPEN IRN_ADM4 and IRN_ADM3

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#922]
Our current ADM4 and ADM3 for IRN is from OSM and lacks full names for many of the polygons. Moving forward, we need a shapefile with verifiable names.

**Comment by MichaelR-geoLab** [comment]
other than open street maps, for the live of me I cannot find a shapefile or even map of Iran's ADM 3 or 4. I will take a break from this for now.
