### ISSUE TITLE
How to include Saint Helena in future releases?

### ISSUE THREAD

**Issue by slfuhrig** [wmgeolab/geoBoundaries#964]
Saint Helena is a territory of Great Britain, but not included in our GBR ADM shapefiles. In the future, we will need to decide if we want to add Saint Helena to our GBR shapefiles or give it its own code and shapefiles (similar to how we deal with Greenland) in order to make things easier for users.

**Comment by leeberryman** [comment]
@slfuhrig from one who works with human geography and population data mostly, I’d prefer that it gets it own polygon and code rather than be included in GBR.  I see this was moved to 5.0 milestone.  If I were to recruit a few extra hands any chance we could get many of the same use cases like this included in 4.0?

**Comment by DanRunfola** [comment]
@leeberryman @slfuhrig 
I had a chance to discuss this with a number of stakeholders, and think we have a reasonably elegant way to handle this.  Essentially, in our ISO code tracking file (https://github.com/wmgeolab/geoBoundaryBot/blob/main/dta/iso_3166_1_alpha_3.csv) we're adding a "Claimant(s)" and "Disputed" column.  So, every entity with an ISO code will be represented as a row; the "Claimants" will cover cases where it's a territory like Saint Helena (i.e., a claimant would be GBR there), and then Saint Helena would have a "No" for disputed.

This lets us reconstruct the data however we (or a user) wants later on.  

Closing this out for now, as we'll really be engaging with this post-4.0 given the number of territories we need to get incorporated, but very high on the priority list.
