### ISSUE TITLE
Grenada Boundary Update

### ISSUE THREAD

**Issue by justinelliotmeyers** [wmgeolab/geoBoundaries#993]
Official Boundaries:
https://grennode.gov.gd/geoserver/web/

![image](https://user-images.githubusercontent.com/5324316/111632779-36a7a780-87cb-11eb-81d7-60d4dba96cad.png)

Need to identify license - I emailed gis.ppu@gmail.com several days ago, but no response.

**Comment by justinelliotmeyers** [comment]
@slfuhrig any thoughts on this?  Thanks!

**Comment by lydiatroup** [comment]
it looks more accurate and credible, but no license info, so we can't use it unless we get email permission for open distribution @justinelliotmeyers

**Comment by lydiatroup** [comment]
Our current boundary matches what is available on HDX and what is shown on google maps. Since there is no license info available on this one, we will keep our current one for the time being.
