### ISSUE TITLE
[BOUNDARY ERRATA] Hong Kong is missing a shape in ADM0 & ADM1

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#995]
**Describe the Error**
A clear and concise description of what the error is - please provide sources as appropriate.

Hong Kong is missing a shape in ADM0 & ADM1 in geoBoundariesCGAZ release

**Screenshots**
If applicable, add screenshots or images to help explain your problem.

**Additional context**

**Comment by slfuhrig** [comment]
Thank you for letting us know of the problem! We will have one of our researchers explore the issue, and we will update our boundary as soon as possible.

**Comment by DanRunfola** [comment]
There are a number of territories that are missing right now; we're going to be doing a full pass on these post 4.0.  Closing this out for now, but a fix should be coming pretty soon.
