### ISSUE TITLE
[FEATURE REQUEST] IND contribution

### ISSUE THREAD

**Issue by leeberryman** [wmgeolab/geoBoundaries#996]
I have contributions that would make more detailed admin boundaries available for South Asian countries.  I'm linking to a repo for sample sake.  https://github.com/leeberryman/IND-geodata-current.  This data is out of date at the moment (October 2019).  I have a local version that has recently created districts (admin3 in this linked dataset), but would be ADM2 in GeoBoundary terms. 
 The source of the data is geodata was originally digitized from 2011 census maps, but we have maintained, corrected, and updated to be in line with current admin names described at (https://lgdirectory.gov.in/) over the last 10 years.  Please let me know if this is of interest from the project and I will update and make a pull request accordingly.

**Comment by slfuhrig** [comment]
I believe that this would be of interest, but @DanRunfola can speak more to it than I can. We appreciate your contribution!

**Comment by leeberryman** [comment]
@DanRunfola I made a pull request with IND_ADM2 first with the meta.txt file and formatting based on what I see here in the repo.  Let me know if there is anything that I should do differently for future pull requests.  After I have successfully finished one pull request I'll start working on other areas that I could help with data.

**Comment by leeberryman** [comment]
@DanRunfola looks like it didn’t like the format of my meta.txt file

**Comment by leeberryman** [comment]
@lydiatroup I have changed the license.png as requested

**Comment by DanRunfola** [comment]
Closing this out of issues; we'll handle the conversation around this contribution in the PR.  No need to create an issue if you're creating a PR anyway (we use issues to track things that aren't being done in the immediate future).
